window.ethicsData = {
  // ==========================================================
  // القسم الأول: Ethics - Part 1
  // ==========================================================
  ethics_1: {
    title: "Ethics in Nursing - Part 1",
    questions: [
      { q: "A nurse is caring for a patient who refuses a dressing change after understanding the risks and benefits. The nurse respects the decision and documents it. Which ethical principle is the nurse demonstrating?", type: "mcq", options: ["Beneficence", "Autonomy", "Justice", "Veracity", "Accountability"], a: 1, hint: "This principle means respecting a patient’s right to make informed decisions about their care." },
      { q: "A nurse administers medication without explaining the purpose or side effects. Which patient right is violated?", type: "mcq", options: ["Right to confidentiality", "Right to continuity of care", "Right to informed consent", "Right to refuse treatment", "Right to privacy"], a: 2, hint: "Patients must receive information about risks, benefits, and purpose before treatment." },
      { q: "A nurse accidentally gives a wrong dose of medication and immediately reports the incident to the supervisor. What ethical action is demonstrated?", type: "mcq", options: ["Justice", "Accountability", "Veracity", "Fidelity", "Autonomy"], a: 1, hint: "Nurses must accept responsibility for their actions and report errors according to the code of ethics." },
      { q: "A student nurse performs a sterile procedure without supervision and the patient develops an infection. Which legal issue applies?", type: "mcq", options: ["Slander", "Malpractice", "Battery", "Assault", "False imprisonment"], a: 1, hint: "This occurs when a professional fails to meet expected standards, resulting in harm." },
      { q: "A nurse refuses to share a patient’s HIV status with a visitor who asks. Which nursing value is upheld?", type: "mcq", options: ["Promoting justice", "Preserving dignity", "Maintaining confidentiality", "Promoting well-being", "Accountability"], a: 2, hint: "Nurses must protect confidential information per ethical responsibilities." },
      { q: "A patient complains that the physician’s explanation was unclear. The nurse clarifies the information to support understanding. Which code element is demonstrated?", type: "mcq", options: ["Nurses and coworkers", "Nurses and practice", "Nurses and people", "Nurses and profession", "None of the above"], a: 2, hint: "Nurses ensure patients receive enough information for informed decisions." },
      { q: "A nurse documents care before it is completed. This action may lead to:", type: "mcq", options: ["Assault", "Libel", "Negligence", "Slander", "Battery"], a: 2, hint: "Incorrect or inaccurate documentation is a common issue in negligence and malpractice cases." },
      { q: "A nurse restrains a confused patient without a physician order. What legal violation occurred?", type: "mcq", options: ["Assault", "Battery", "False imprisonment", "Defamation", "Malice"], a: 2, hint: "Restricting a patient’s movement without legal justification constitutes this." },
      { q: "During an ethical dilemma, the healthcare team gathers to discuss options and consequences. This represents:", type: "mcq", options: ["Ethical committee function", "Autonomy", "Accountability", "Advocacy", "Justice"], a: 0, hint: "These committees facilitate discussion and resolution of ethical dilemmas." },
      { q: "A nurse speaks loudly about a patient’s diagnosis in a hallway. Which tort is committed?", type: "mcq", options: ["Assault", "Libel", "Invasion of privacy", "False imprisonment", "Malpractice"], a: 2, hint: "Sharing confidential information publicly violates this right." },
      { q: "A nurse chooses to provide care equally to all patients regardless of background. Which ethical value is demonstrated?", type: "mcq", options: ["Justice", "Fidelity", "Veracity", "Beneficence", "Confidentiality"], a: 0, hint: "This value means fairness and equity in nursing practice." },
      { q: "A patient refuses a blood transfusion for religious reasons. The nurse supports this decision. What principle is upheld?", type: "mcq", options: ["Beneficence", "Non-maleficence", "Autonomy", "Justice", "Confidentiality"], a: 2, hint: "Patients have the right to make decisions based on cultural and religious beliefs." },
      { q: "A nurse reviews a patient’s chart from curiosity, not for care purposes. This violates:", type: "mcq", options: ["Right to informed consent", "Right to privacy/confidentiality", "Right to continuity of care", "Right to respectful care", "Right to refuse treatment"], a: 1, hint: "Confidential records must only be accessed for clinical reasons." },
      { q: "A nurse threatens a patient with withholding pain medication if they don't stay in bed. This is an example of:", type: "mcq", options: ["Assault", "Battery", "Negligence", "Malpractice", "Libel"], a: 0, hint: "This is the threat of harm without physical contact." },
      { q: "A nurse physically forces medication on a competent adult patient. This is:", type: "mcq", options: ["Assault", "Battery", "Malpractice", "Negligence", "False imprisonment"], a: 1, hint: "This involves unwanted physical contact or treatment without consent." },
      { q: "A nurse stays updated through workshops and continuing education. This reflects which ICN element?", type: "mcq", options: ["Nurses and coworkers", "Nurses and practice", "Nurses and people", "Nurses and profession", "Nurses and ethics"], a: 1, hint: "Nurses must maintain competence through continual learning." },
      { q: "A nurse assigns a task to a nursing assistant who is not trained for it. A patient is injured. This is an example of:", type: "mcq", options: ["Delegation", "Accountability breach", "Justice", "Autonomy", "Confidentiality"], a: 1, hint: "Nurses must use judgment regarding individual competence when delegating tasks." },
      { q: "A patient requests to see his medical bill and understand charges. What right is this?", type: "mcq", options: ["Right to continuity of care", "Right to privacy", "Right to examine bills", "Right to refuse research", "Right to confidentiality"], a: 2, hint: "Patients have the right to review and understand their hospital bills." },
      { q: "A nurse reports a coworker suspected of drug diversion. This action reflects:", type: "mcq", options: ["Justice", "Accountability", "Autonomy", "Beneficence", "Confidentiality"], a: 1, hint: "Nurses must safeguard individuals when their health is endangered by coworkers." },
      { q: "A healthcare team discusses treatment options with the patient’s family while respecting patient wishes. This demonstrates:", type: "mcq", options: ["Ethical dilemma", "Collaborative decision-making", "Negligence", "Fidelity", "Informed refusal"], a: 1, hint: "Collaborative ethical reasoning includes patients, families, and health professionals." }
    ]
  },
  // ==========================================================
  // القسم الثاني: Ethics - Part 2
  // ==========================================================
  ethics_2: {
    title: "Ethics in Nursing - Part 2",
    questions: [
      { q: "A nurse refuses to participate in a procedure that violates her ethical beliefs but ensures patient care is not compromised. What ethical concept applies?", type: "mcq", options: ["Autonomy (nurse)", "Justice", "Veracity", "Accountability", "Fidelity"], a: 0, hint: "Nurses may refuse participation in activities that conflict with ethical values as long as patient safety is maintained." },
      { q: "A nurse fails to raise bedside rails for a confused patient who later falls. This is an example of:", type: "mcq", options: ["Assault", "Negligence", "Libel", "Battery", "Slander"], a: 1, hint: "This is failure to provide care that a reasonable nurse would in similar circumstances." },
      { q: "A patient undergoing research treatment is informed they may withdraw at any time. What patient right is reinforced?", type: "mcq", options: ["Right to privacy", "Right to refuse treatment", "Right to confidentiality", "Right to informed consent", "Right to continuity of care"], a: 3, hint: "Research requires separate informed consent, including right to withdraw at any time." },
      { q: "A nurse tells a colleague that a patient is “insane” without clinical evidence. What type of defamation is this?", type: "mcq", options: ["Libel", "Battery", "Assault", "Slander", "Malice"], a: 3, hint: "This term refers to spoken defamation of character." },
      { q: "A nurse participates in continuing education to improve patient safety. Which nursing value applies?", type: "mcq", options: ["Justice", "Competence", "Autonomy", "Veracity", "Advocacy"], a: 1, hint: "Nurses must maintain this value through lifelong learning." },
      { q: "A nurse threatens to restrain a patient who refuses medication. Which tort is involved?", type: "mcq", options: ["Battery", "Assault", "Libel", "Defamation", "Malpractice"], a: 1, hint: "This involves threats causing fear of harm without physical touch." },
      { q: "A nurse ignores a patient’s call light for an extended time resulting in injury. What occurred?", type: "mcq", options: ["Malpractice", "False imprisonment", "Negligence", "Advocacy", "Autonomy"], a: 2, hint: "Failure to respond promptly to patient needs constitutes this." },
      { q: "A patient asks the nurse to keep his diagnosis confidential. The nurse honors this. What principle is shown?", type: "mcq", options: ["Justice", "Confidentiality", "Accountability", "Autonomy", "Veracity"], a: 1, hint: "Maintaining this is a fundamental ethical obligation in nursing." },
      { q: "A nurse provides treatment based on patient needs without discrimination. What value is being demonstrated?", type: "mcq", options: ["Veracity", "Justice", "Accountability", "Fidelity", "Autonomy"], a: 1, hint: "This value ensures fairness and equity in care delivery." },
      { q: "A nurse openly discusses a patient’s lab results in the cafeteria. This violates:", type: "mcq", options: ["Informed consent", "Privacy", "Autonomy", "Justice", "Advocacy"], a: 1, hint: "Confidential information must be protected from unauthorized disclosure." },
      { q: "A nurse provides extra materials to help a patient understand a new diagnosis. This reflects:", type: "mcq", options: ["Informed consent support", "Non-maleficence", "Justice", "Accountability", "Confidentiality"], a: 0, hint: "Patients have the right to receive information necessary for informed decision-making." },
      { q: "A nurse administers medication despite the patient clearly stating “No.” What tort occurred?", type: "mcq", options: ["Battery", "Slander", "Assault", "Negligence", "Malice"], a: 0, hint: "Giving treatment without consent is this, an intentional tort." },
      { q: "A nurse tells a student, “Always consider cultural beliefs before explaining treatment.” Which patient right does this support?", type: "mcq", options: ["Right to continuity", "Right to respectful care", "Right to confidentiality", "Right to informed consent", "Right to privacy"], a: 1, hint: "This right includes honoring beliefs, values, and customs." },
      { q: "A nurse suspects a coworker is intoxicated and unable to safely perform duties. What should the nurse do first?", type: "mcq", options: ["Report to supervisor", "Document anonymously", "Confront in front of patient", "Ignore the situation", "Notify the media"], a: 0, hint: "Nurses must safeguard public safety and report unsafe practice." },
      { q: "A nurse gives a patient’s clinical file to an unauthorized person. This is:", type: "mcq", options: ["Malpractice", "Negligence", "Defamation", "Breach of confidentiality", "Battery"], a: 3, hint: "Confidential information must only be disclosed to authorized individuals." },
      { q: "A patient refuses a diagnostic procedure. The nurse supports his decision and informs the doctor. This demonstrates:", type: "mcq", options: ["Non-maleficence", "Autonomy", "Fidelity", "Accountability", "Competence"], a: 1, hint: "Patients have the right to refuse treatment even after being informed of consequences." },
      { q: "A patient is denied services due to insurance limitations. Which ethical value is violated?", type: "mcq", options: ["Justice", "Fidelity", "Autonomy", "Confidentiality", "Accountability"], a: 0, hint: "This value relates to fairness and equal access to care." },
      { q: "A nurse carefully explains a procedure and ensures the patient understands. This action supports:", type: "mcq", options: ["Accountability", "Informed consent", "Beneficence", "Justice", "Fidelity"], a: 1, hint: "Providing adequate information is essential for this right." },
      { q: "A nurse witnesses a doctor verbally abusing a patient but does nothing. This violates:", type: "mcq", options: ["Beneficence", "Justice", "Accountability", "Advocacy", "Confidentiality"], a: 3, hint: "Nurses must advocate to protect patients from harm or abuse." },
      { q: "A nurse documents care factually and without personal opinions. This follows:", type: "mcq", options: ["Ethical reasoning", "Legal reporting standards", "Documentation guidelines", "Regulatory law", "Institutional policy"], a: 2, hint: "Clear, factual, objective documentation prevents liability and supports patient safety." }
    ]
  },
  // ==========================================================
  // القسم الثالث: Ethics - Part 3
  // ==========================================================
  ethics_3: {
    title: "Ethics in Nursing - Part 3",
    questions: [
      { q: "A nurse carefully checks patient identity and allergies before giving medication. Which ethical principle is demonstrated?", type: "mcq", options: ["Veracity", "Justice", "Beneficence", "Accountability", "Autonomy"], a: 2, hint: "This principle means doing good and preventing harm, which includes safe medication administration." },
      { q: "A nurse accidentally discloses a patient’s diagnosis to another patient in the room. This represents:", type: "mcq", options: ["False imprisonment", "Battery", "Confidentiality breach", "Negligence", "Malpractice"], a: 2, hint: "This is a core ethical responsibility and must be maintained at all times." },
      { q: "A nurse fails to monitor a patient after administering sedatives, leading to respiratory depression. What occurred?", type: "mcq", options: ["Assault", "Malpractice", "Slander", "False imprisonment", "Justice violation"], a: 1, hint: "This is professional negligence leading to patient harm." },
      { q: "A patient asks the nurse, “Do I have the right to refuse this treatment?” The nurse replies, “Yes, as long as you understand the consequences.” This reflects:", type: "mcq", options: ["Advocacy", "Justice", "Autonomy", "Veracity", "Beneficence"], a: 2, hint: "This principle involves the patient’s right to choose or refuse care after informed discussion." },
      { q: "A nurse provides care to a patient from a different culture and accommodates religious practices. What patient right is upheld?", type: "mcq", options: ["Privacy", "Confidentiality", "Respectful care", "Refusal of treatment", "Continuity of care"], a: 2, hint: "This right includes considering culture, beliefs, and preferences." },
      { q: "A nurse intentionally leaves out abnormal findings in documentation to avoid criticism. This may result in:", type: "mcq", options: ["Malpractice", "Assault", "Libel", "False imprisonment", "Slander"], a: 0, hint: "Inaccurate or incomplete documentation can contribute to this liability." },
      { q: "A nurse gives the wrong medication but chooses not to report it. Which ethical value is violated?", type: "mcq", options: ["Beneficence", "Justice", "Accountability", "Fidelity", "Autonomy"], a: 2, hint: "Nurses are accountable for their actions and must report errors responsibly." },
      { q: "A patient is left uninformed about a procedure’s risks. What right is violated?", type: "mcq", options: ["Right to privacy", "Right to dignity", "Right to informed consent", "Right to continuity", "Right to respectful care"], a: 2, hint: "This right requires disclosure of risks, benefits, and alternatives." },
      { q: "A nurse prevents a patient from leaving the hospital by blocking the door. What tort occurred?", type: "mcq", options: ["Battery", "Assault", "False imprisonment", "Malpractice", "Negligence"], a: 2, hint: "Preventing a patient from leaving without legal justification is this." },
      { q: "A nurse joins an ethics committee discussion about a serious treatment dilemma. What role is the committee serving?", type: "mcq", options: ["Punishment", "Confidentiality enforcement", "Facilitating dialogue", "Legal decision-making", "Treatment authorization"], a: 2, hint: "These committees provide structure and discussion about ethical dilemmas." },
      { q: "A nurse tells a patient, “I will return in 15 minutes,” and does so. This demonstrates:", type: "mcq", options: ["Accountability", "Fidelity", "Autonomy", "Beneficence", "Justice"], a: 1, hint: "This principle means keeping promises and commitments to patients." },
      { q: "A patient’s family requests information, but the patient says, “Do NOT tell them.” The nurse must:", type: "mcq", options: ["Inform the family anyway", "Follow the patient’s wishes", "Ask the doctor for permission", "Tell only partial information", "Avoid addressing the issue"], a: 1, hint: "Patient autonomy and confidentiality must be honored unless safety is at risk." },
      { q: "A nurse writes false statements about a coworker in a report, damaging the coworker’s reputation. This is:", type: "mcq", options: ["Slander", "Battery", "Libel", "Malpractice", "Negligence"], a: 2, hint: "This term refers to written defamation of character." },
      { q: "A patient’s call light is ignored repeatedly, and the patient falls trying to get up alone. This is an example of:", type: "mcq", options: ["Malpractice", "Negligence", "Assault", "Battery", "Defamation"], a: 1, hint: "This is failure to act as a reasonable nurse would in similar circumstances." },
      { q: "A nurse provides translated materials for a non-English-speaking patient. Which value is demonstrated?", type: "mcq", options: ["Competence", "Accountability", "Respect for dignity", "Justice", "Fidelity"], a: 3, hint: "This principle ensures equitable access to information and services." },
      { q: "A nurse reports a colleague who repeatedly violates safety procedures. This reflects:", type: "mcq", options: ["Advocacy", "Justice", "Accountability", "Autonomy", "Fidelity"], a: 2, hint: "Nurses must act to safeguard patients and report unsafe behavior." },
      { q: "A patient requires explanation of hospital rules on admission. Which right is being fulfilled?", type: "mcq", options: ["Right to documentation", "Right to informed consent", "Right to know hospital policies", "Right to privacy", "Right to research information"], a: 2, hint: "Patients must be informed of relevant institutional rules and regulations." },
      { q: "A nurse educates a patient about alternatives to a proposed therapy. This demonstrates:", type: "mcq", options: ["Beneficence", "Veracity", "Autonomy support", "Justice", "Confidentiality"], a: 2, hint: "Supporting informed decision-making strengthens this patient principle." },
      { q: "A nurse gives a harmful treatment incorrectly, violating both the duty of care and causing injury. This fulfills:", type: "mcq", options: ["All elements of malpractice", "Battery", "Assault", "False imprisonment", "Defamation"], a: 0, hint: "This requires duty, breach, causation, and damages—all present here." },
      { q: "A nurse allows patients to participate in decisions about their own health. This directly supports:", type: "mcq", options: ["Advocacy", "Justice", "Autonomy", "Fidelity", "Accountability"], a: 2, hint: "This principle involves respecting and encouraging patient participation in decisions." }
    ]
  },
  // ==========================================================
  // القسم الرابع: Ethics - Part 4
  // ==========================================================
  ethics_4: {
    title: "Ethics in Nursing - Part 4",
    questions: [
      { q: "A nurse ensures that patient data are stored securely and not accessible to unauthorized persons. Which value is demonstrated?", type: "mcq", options: ["Advocacy", "Autonomy", "Confidentiality", "Justice", "Respectful care"], a: 2, hint: "Protecting patient information is a core ethical requirement in nursing practice." },
      { q: "A nurse administers medication even though the patient clearly states they do not want it. This is an example of:", type: "mcq", options: ["Assault", "Battery", "Negligence", "Malpractice", "Defamation"], a: 1, hint: "This is intentional touching or treatment without consent." },
      { q: "A nurse checks the patient thoroughly for understanding before obtaining their signature on a consent form. This respects:", type: "mcq", options: ["Justice", "Informed consent", "Non-maleficence", "Accountability", "Respectful care"], a: 1, hint: "This requires clear, understandable information before the patient agrees to treatment." },
      { q: "A nurse provides equal care to two patients regardless of their financial backgrounds. Which ethical principle is followed?", type: "mcq", options: ["Beneficence", "Fidelity", "Justice", "Autonomy", "Veracity"], a: 2, hint: "This principle means fairness and equity in healthcare delivery." },
      { q: "A nurse suspects child abuse and reports it immediately according to hospital policy. This action represents:", type: "mcq", options: ["Autonomy", "Beneficence", "Justice", "Accountability", "Fidelity"], a: 3, hint: "Nurses must follow legal reporting requirements to protect patient safety." },
      { q: "A nurse accepts a task despite not having the competency to perform it safely. An injury results. What is this?", type: "mcq", options: ["Malice", "Negligence", "Assault", "Slander", "Battery"], a: 1, hint: "This includes accepting responsibilities beyond one’s competence, resulting in harm." },
      { q: "A patient refuses a recommended treatment. The nurse explains possible consequences but respects the decision. What principle is upheld?", type: "mcq", options: ["Justice", "Autonomy", "Accountability", "Confidentiality", "Beneficence"], a: 1, hint: "Patients have the right to refuse treatment after being informed of consequences." },
      { q: "A coworker asks the nurse for details about a patient they are not assigned to. The nurse refuses. This shows:", type: "mcq", options: ["Fidelity", "Justice", "Respect", "Confidentiality", "Autonomy"], a: 3, hint: "Only authorized personnel may access private patient information." },
      { q: "A nurse speaks rudely to a patient who requests assistance. Which patient right is violated?", type: "mcq", options: ["Right to respectful care", "Right to refusal", "Right to privacy", "Right to confidentiality", "Right to research consent"], a: 0, hint: "Patients have the right to receive considerate and respectful care at all times." },
      { q: "A nurse reviews a patient’s chart for curiosity, not for clinical reasons. This is:", type: "mcq", options: ["Assault", "Negligence", "Invasion of privacy", "Battery", "False imprisonment"], a: 2, hint: "Accessing information without clinical justification violates privacy/confidentiality rules." },
      { q: "A nurse delegates wound care to a nursing assistant who is not trained for the task. Harm occurs. What is this?", type: "mcq", options: ["Battery", "Negligence", "Malpractice", "Assault", "Slander"], a: 2, hint: "Improper delegation that results in harm is considered this (professional negligence)." },
      { q: "A patient becomes upset after overhearing staff discuss their condition in the hallway. What right was violated?", type: "mcq", options: ["Right to privacy", "Right to informed consent", "Right to continuity of care", "Right to respectful care", "Right to research refusal"], a: 0, hint: "Discussions about patient conditions must be held confidentially and in private areas." },
      { q: "A nurse tells a patient all possible outcomes of a procedure honestly, even the unpleasant ones. This demonstrates:", type: "mcq", options: ["Fidelity", "Veracity", "Justice", "Confidentiality", "Beneficence"], a: 1, hint: "This principle requires telling the truth to support patient decision-making." },
      { q: "A nurse fails to assess a patient’s vital signs after surgery despite being instructed to do so. This is:", type: "mcq", options: ["Negligence", "Defamation", "Assault", "Battery", "False imprisonment"], a: 0, hint: "Failure to perform necessary assessments is this, a breach of duty." },
      { q: "An ethics committee meets to evaluate a case involving refusal of life-saving treatment. This committee is helping by:", type: "mcq", options: ["Determining punishment", "Providing ethical guidance", "Approving treatment", "Designing hospital policies only", "Conducting legal enforcement"], a: 1, hint: "These committees help structure decisions around ethical dilemmas in patient care." },
      { q: "A nurse places a professional boundary and avoids sharing personal information with a patient. This action demonstrates:", type: "mcq", options: ["Fidelity", "Accountability", "Respect for dignity", "Justice", "Veracity"], a: 2, hint: "Preserving this includes maintaining professional boundaries." },
      { q: "A patient requests a second opinion before surgery. The nurse encourages this. Which principle is applied?", type: "mcq", options: ["Accountability", "Autonomy", "Fidelity", "Beneficence", "Confidentiality"], a: 1, hint: "Supporting the patient's ability to make informed choices reinforces this principle." },
      { q: "A nurse comments publicly, “That patient is crazy,” in front of visitors. This is:", type: "mcq", options: ["Battery", "Assault", "Slander", "Negligence", "Fraud"], a: 2, hint: "Verbal defamatory statements are considered this." },
      { q: "While assisting a patient, the nurse ensures a private environment during physical examination. Which right is upheld?", type: "mcq", options: ["Right to autonomy", "Right to privacy", "Right to informed consent", "Right to confidentiality", "Right to participation"], a: 1, hint: "The patient has the right to physical and informational privacy during care." },
      { q: "A nurse advocates for patient safety after noticing unsafe equipment in the unit. This represents:", type: "mcq", options: ["Justice", "Advocacy", "Beneficence", "Fidelity", "Confidentiality"], a: 1, hint: "Nurses must advocate for safe environments to protect patient well-being." }
    ]
  },
  // ==========================================================
  // القسم الخامس: Ethics - Part 5
  // ==========================================================
  ethics_5: {
    title: "Ethics in Nursing - Part 5",
    questions: [
      { q: "A nurse schedules procedures in a way that ensures the patient’s hospital stay is efficient and not prolonged unnecessarily. Which patient right is being met?", type: "mcq", options: ["Right to privacy", "Right to respectful care", "Right to continuity of care", "Right to reasonable service response", "Right to informed refusal"], a: 3, hint: "Patients have the right to expect hospitals to provide services in a timely and reasonable manner." },
      { q: "A patient tells the nurse a physician explained the treatment too quickly. The nurse rewrites the instructions in simpler terms. This supports:", type: "mcq", options: ["Advocacy", "Justice", "Confidentiality", "Accountability", "Fidelity"], a: 0, hint: "Nurses help patients understand care and advocate for informed decision-making." },
      { q: "A nurse restrains a patient without a physician’s order “to keep them calm.” This is:", type: "mcq", options: ["Battery", "Assault", "False imprisonment", "Negligence", "Slander"], a: 2, hint: "Using restraints without legal justification constitutes this." },
      { q: "A nurse is caring for a psychiatric patient who requests to keep personal items such as clothing. The nurse respects this. Which patient's right is upheld?", type: "mcq", options: ["Right to confidentiality", "Right to respectful care", "Psychiatric patient’s right to personal belongings", "Right to informed decision", "Right to refuse medication"], a: 2, hint: "Psychiatric patients have the right to maintain clothing and personal effects unless unsafe." },
      { q: "A nurse truthfully tells a patient the potential risks of a lumbar puncture. This is an example of:", type: "mcq", options: ["Autonomy", "Veracity", "Beneficence", "Accountability", "Justice"], a: 1, hint: "This principle requires being honest in presenting information, including risks of procedures." },
      { q: "A nurse witnesses a coworker making a medication error but covering it up. What should the nurse do?", type: "mcq", options: ["Ignore it", "Tell other coworkers", "Report through the chain of command", "Post about it online", "Call the patient’s family"], a: 2, hint: "Nurses must follow procedures for reporting unsafe or unethical conduct." },
      { q: "A patient insists on spiritual rituals before surgery. The nurse arranges for privacy and time. This respects the patient’s:", type: "mcq", options: ["Autonomy only", "Confidentiality only", "Right to confidentiality and autonomy", "Right to respectful care", "Right to informed consent"], a: 3, hint: "This right includes honoring beliefs, customs, and religious practices." },
      { q: "A nurse openly criticizes a patient’s behavior by saying “You are irresponsible” in front of other patients. What is violated?", type: "mcq", options: ["Right to confidentiality", "Right to respectful care", "Right to privacy", "Right to informed consent", "Right to continuity of care"], a: 1, hint: "This right prohibits demeaning language or treatment towards patients." },
      { q: "A nurse explains to a patient that they can refuse participation in a research study without affecting their care. Which right does this reflect?", type: "mcq", options: ["Right to respectful care", "Right to research refusal", "Right to privacy", "Right to informed consent", "Right to continuity"], a: 1, hint: "Patients must consent separately to research and may withdraw at any time." },
      { q: "A patient requests to know the names and qualifications of those caring for them. The nurse provides this information. Which right is upheld?", type: "mcq", options: ["Right to privacy", "Right to informed consent", "Right to information about caregivers", "Right to respectful care", "Right to confidentiality"], a: 2, hint: "Patients have the right to know the identity and qualifications of healthcare providers." },
      { q: "A nurse agrees to follow up with a patient after a diagnostic test but forgets due to busyness. This violates:", type: "mcq", options: ["Justice", "Fidelity", "Beneficence", "Autonomy", "Accountability"], a: 1, hint: "This principle means keeping promises made to patients." },
      { q: "A nurse turns off the call bell in an elderly patient’s room to “avoid being disturbed.” The patient later falls. This is:", type: "mcq", options: ["Assault", "Battery", "False imprisonment", "Negligence", "Libel"], a: 3, hint: "Ignoring patient safety needs is this and may lead to harm." },
      { q: "A nurse lies to a patient about test results to “keep them calm.” Which principle is violated?", type: "mcq", options: ["Beneficence", "Fidelity", "Veracity", "Autonomy", "Confidentiality"], a: 2, hint: "This principle requires truthfulness in communication with patients." },
      { q: "A nurse fails to follow the five rights of medication administration, resulting in patient harm. This is legally considered:", type: "mcq", options: ["Assault", "Malpractice", "Slander", "Battery", "False imprisonment"], a: 1, hint: "This is professional negligence resulting in patient injury due to breach of duty." },
      { q: "A patient states they do not want family involved in their care. The nurse ensures all discussions occur privately. What is protected?", type: "mcq", options: ["Confidentiality", "Privacy", "Autonomy", "Justice", "All of the above"], a: 4, hint: "Respecting this request upholds autonomy, privacy, and confidentiality simultaneously." },
      { q: "A nurse avoids performing a sterile procedure they are unfamiliar with and asks for supervision instead. This shows:", type: "mcq", options: ["Autonomy", "Accountability", "Justice", "Negligence", "Fidelity"], a: 1, hint: "This includes recognizing limitations and seeking supervision to maintain patient safety." },
      { q: "A nurse purposely delays administering pain medication to a patient who requested it. This is an example of:", type: "mcq", options: ["Assault", "Battery", "Negligence", "Abuse", "Defamation"], a: 3, hint: "Intentionally withholding needed care is a form of patient abuse." },
      { q: "A nurse uses judgment to delegate tasks only to staff who are competent. This fulfills which ICN element?", type: "mcq", options: ["Nurses and people", "Nurses and profession", "Nurses and practice", "Nurses and coworkers", "Nurses and ethics"], a: 2, hint: "Nurses and practice includes using judgment regarding competence in delegation." },
      { q: "A nurse reviews facts, alternative actions, and likely consequences before making a decision in a difficult case. This is:", type: "mcq", options: ["Advocacy", "Ethical reasoning", "Autonomy", "Veracity", "Beneficence"], a: 1, hint: "This is a systematic review of actions, principles, and consequences for justified decisions." },
      { q: "A patient asks if their hospital is connected to a university. The nurse explains its educational affiliation. This honors which right?", type: "mcq", options: ["Right to respectful care", "Right to continuity", "Right to be informed of hospital relationships", "Right to privacy", "Right to confidentiality"], a: 2, hint: "Patients have the right to know institutional affiliations that may affect care." }
    ]
  },
  // ==========================================================
  // القسم السادس: Ethics - Part 6
  // ==========================================================
  ethics_6: {
    title: "Ethics in Nursing - Part 6",
    questions: [
      { q: "A patient demands to review his medical chart. The nurse confirms his identity and allows supervised review. What right is being respected?", type: "mcq", options: ["Right to privacy", "Right to respectful care", "Right to access medical information", "Right to continuity", "Right to informed refusal"], a: 2, hint: "Patients have the right to review and understand information related to their care." },
      { q: "A nurse shares false written statements about a coworker’s competence in a report. What is this?", type: "mcq", options: ["Slander", "Libel", "Assault", "Battery", "Negligence"], a: 1, hint: "This term refers to written defamation of character." },
      { q: "A nurse decides not to medicate a patient because “they complain too much,” even though the medication is ordered. This is:", type: "mcq", options: ["Assault", "Negligence", "Abuse", "Malpractice", "Battery"], a: 2, hint: "Intentionally withholding treatment constitutes patient abuse." },
      { q: "A patient who does not speak the local language receives information through an interpreter. Which ethical principle is supported?", type: "mcq", options: ["Justice", "Autonomy", "Beneficence", "Veracity", "Confidentiality"], a: 0, hint: "This principle requires equitable access to information and services for all patients." },
      { q: "A nurse reports a coworker whose poor hygiene practices endanger patient health. Which ICN element is this?", type: "mcq", options: ["Nurses and people", "Nurses and coworkers", "Nurses and practice", "Nurses and profession", "Nurses and community"], a: 1, hint: "Nurses must take action when coworkers endanger individuals, families, or communities." },
      { q: "A patient refuses treatment after fully understanding the risks. The nurse documents the refusal and informs the physician. Which principle applies?", type: "mcq", options: ["Fidelity", "Non-maleficence", "Autonomy", "Justice", "Beneficence"], a: 2, hint: "Patients have the right to refuse treatment after receiving adequate information." },
      { q: "A nurse follows hospital policy for documenting incident reports. This relates to:", type: "mcq", options: ["Regulatory law", "Criminal law", "Intentional torts", "Ethics only", "Advocacy"], a: 0, hint: "Administrative/regulatory law governs institutional policies like incident reporting." },
      { q: "A nurse provides an honest explanation of alternative treatments and their risks. This demonstrates:", type: "mcq", options: ["Veracity", "Autonomy", "Fidelity", "Confidentiality", "Advocacy"], a: 0, hint: "This principle requires truthful communication regarding options and risks." },
      { q: "A nurse fails to renew CPR training and performs incorrect chest compressions leading to patient harm. This is:", type: "mcq", options: ["Assault", "Battery", "Malpractice", "False imprisonment", "Libel"], a: 2, hint: "Failure to maintain competency falls under this when harm occurs." },
      { q: "A pediatric patient receives care by qualified children’s nurses, honoring which right?", type: "mcq", options: ["Child’s right to confidentiality", "Child’s right to specialized pediatric care", "Child’s right to refuse treatment", "Child’s right to privacy", "Child’s right to continuity"], a: 1, hint: "Children have the right to receive age-appropriate, specialized care." },
      { q: "A nurse maintains professional boundaries despite a patient offering personal gifts. Which ethical value is strengthened?", type: "mcq", options: ["Justice", "Dignity", "Veracity", "Accountability", "Beneficence"], a: 1, hint: "Preserving this requires maintaining appropriate professional boundaries." },
      { q: "During an emergency, a nurse acts as the liaison between patient and physician, ensuring clear communication. This reflects:", type: "mcq", options: ["Fidelity", "Accountability", "Advocacy", "Autonomy", "Justice"], a: 2, hint: "The nurse’s major focus is protecting patients’ rights as their advocate." },
      { q: "A nurse deliberately charts assessment data that was not actually performed. This is:", type: "mcq", options: ["Negligence", "Assault", "Battery", "Fraud", "Slander"], a: 3, hint: "This includes intentional misrepresentation or false documentation in healthcare." },
      { q: "A nurse reports a suspicious death following hospital policy. This is an example of complying with:", type: "mcq", options: ["Criminal law", "Statutory law", "Common law", "Regulatory law", "Ethical guidelines only"], a: 1, hint: "These laws include mandatory reporting requirements for certain events." },
      { q: "A nurse ensures that the environment is safe and free from hazards. Which ICN element is addressed?", type: "mcq", options: ["Nurses and coworkers", "Nurses and practice", "Nurses and people", "Nurses and profession", "Nurses and environment"], a: 2, hint: "Nurses must promote environments that respect human rights, safety, and well-being." },
      { q: "A patient wants to record a discussion with the nurse. The nurse explains privacy implications and obtains consent. This follows:", type: "mcq", options: ["Justice", "Autonomy", "Confidentiality", "Fidelity", "Veracity"], a: 2, hint: "Recording healthcare interactions involves confidentiality and consent." },
      { q: "A nurse carefully reports all abnormal changes in patient condition to the physician immediately. This prevents:", type: "mcq", options: ["Slander", "Assault", "Negligence", "Libel", "False imprisonment"], a: 2, hint: "Prompt communication of changes prevents this and protects patient safety." },
      { q: "A nurse explains to a student the importance of documenting facts, not opinions. This aligns with:", type: "mcq", options: ["Legal documentation standards", "Ethical decision-making", "Autonomy", "Confidentiality only", "Justice"], a: 0, hint: "Objective, factual documentation is crucial to avoid legal liability." },
      { q: "A patient who is involved in a clinical trial wants to discontinue participation. The nurse ensures that withdrawal occurs safely. Which right is this?", type: "mcq", options: ["Right to continuity", "Right to fair billing", "Right to refuse research participation", "Right to privacy", "Right to respectful care"], a: 2, hint: "Patients may decline or withdraw from research at any time without penalty." },
      { q: "A nurse ensures a patient has adequate privacy during bathing even when the unit is busy. This respects:", type: "mcq", options: ["Confidentiality", "Autonomy", "Justice", "Privacy", "Veracity"], a: 3, hint: "This includes protecting patients from unnecessary exposure during care procedures." }
    ]
  }
};
