window.fundamentalData = {
  // ==========================================================
  // القسم الأول: ميكانيكا الجسم والحركة
  // ==========================================================
  fundamental_mechanics_1: {
    title: "Body Mechanics - Part 1",
    questions: [
      { q: "The primary purpose of using proper body mechanics in nursing?", type: "mcq", options: ["To increase the speed of patient transfer", "To ensure the comfort of health care provider", "To minimize the risk of injury to both the patient and nurse", "To reduce the need for assistive devices"], a: 2, hint: "الهدف دائمًا هو سلامة المريض والممرض معًا." },
      { q: "What can improper body mechanics lead to for health care workers?", type: "mcq", options: ["Increased risk for injury", "Improved patient care", "Higher job satisfaction", "Better communication"], a: 0, hint: "الاستخدام الخاطئ للجسم يؤدي مباشرة إلى ضرر جسدي." },
      { q: "How do proper body mechanics contribute to effective nursing care?", type: "mcq", options: ["By promoting efficient movement and reducing fatigue", "By making tasks more challenging", "By limiting patient interaction", "By increasing time required for tasks"], a: 0, hint: "عندما تقلل من إجهادك، تتحسن كفاءتك." },
      { q: "In order to prevent thrombophlebitis, we teach our patient not to:", type: "mcq", options: ["Cross their eyes when sleeping", "Cross their arms when standing up", "Cross their legs when sitting", "Cross the road when the train is passing"], a: 2, hint: "هذه الوضعية تضغط على الأوردة وتعيق تدفق الدم في الساقين." },
      { q: ".....Muscles and..... system maintain equilibrium or balance which facilitates appropriate body alignment when lifting, bending, moving and doing other activites", type: "mcq", options: ["Skeletal, nervous", "Cardiac, propicetary", "Tissue, vestibular", "Striated, skeletal"], a: 0, hint: "نحن بحاجة إلى العضلات (Skeletal) والإشارات العصبية (Nervous) للحفاظ على التوازن." },
      { q: "Field of physiology that studies muscular actions and the functions of muscles in maintain the posture of body", type: "mcq", options: ["Physiological dynamics", "Body mechanics", "Body kinetics", "Kinesiology"], a: 1, hint: "المصطلح يصف 'ميكانيكية' أو 'آلية' عمل الجسم." },
      { q: "what do the dorsal supine and dorsal recumbent positions have in common?", type: "mcq", options: ["Both require lying on back", "Both have extremities moderately flexed", "The head of bed is raised 45 degree", "The bed is at lowest position"], a: 0, hint: "كلمة 'Dorsal' تعني الاستلقاء على الظهر." },
      { q: "When planning to move a patient, two workers lifting together will......", type: "mcq", options: ["Reduce work load by 50%", "Make work less boring", "Provide patient with more comfort", "Allow more time to do things"], a: 0, hint: "مشاركة الحمل هي الفائدة المباشرة للعمل الجماعي." },
      { q: "when lifting a patient, why are we asked to use our arms and legs and not our back?", type: "mcq", options: ["There really is no difference between the use of back or arms and legs", "Arms and legs are more flexible than our back", "Leg muscles are stronger, larger muscles capable of greater work without injury", "The arms and legs have a better leverage to pull a weight"], a: 2, hint: "عضلات الساقين هي أقوى مجموعة عضلية في الجسم ومصممة لحمل الأوزان." },
      { q: "which of the following is contraindicated against good body mechanics?", type: "mcq", options: ["Avoid bending from waist because this will in time strain the lower back", "Work at a height or level that is comfortable and easy for you", "Carry objects away from the midline of your body and try to reach as far as possible", "Know the maximum weight that is safe to carry"], a: 2, hint: "هذا الفعل يزيد من الضغط على ظهرك وذراعيك بشكل كبير." },
      { q: "which of the following is an effect of mobility?", type: "mcq", options: ["Increased peristalsis", "Constipation", "Poor circulation", "Low blood pressure"], a: 0, hint: "الحركة (Mobility) لها تأثير إيجابي على الجهاز الهضمي." },
      { q: "What is the term for the breakdown of skin tissue due to lack of oxygen supply?", type: "mcq", options: ["Decubitus ulcers", "Contracture", "Orthostatic hypotension", "Constipation"], a: 0, hint: "هذا هو المصطلح الطبي لقرح الفراش." },
      { q: "Prolonged immobility can lead to several complications. Which of the following is a potential consequence?", type: "mcq", options: ["Improved muscle strength", "Enhanced physical conditioning", "Muscle atrophy (wasting away) or contractures", "Faster recovery times"], a: 2, hint: "قلة الحركة (Immobility) تؤدي إلى ضمور العضلات." },
      { q: "A 35-year-old female patient presents to the clinic with fatigue, pallor, and shortness of breath... a specific component of the musculoskeletal system plays a crucial role in the production of red blood cells. Which of the following components is responsible for this function?", type: "mcq", options: ["Bones", "Muscles", "Ligaments", "tendons"], a: 0, hint: "نخاع العظم هو المصنع لجميع خلايا الدم." },
      { q: "What is the primary function of the muscular system?", type: "mcq", options: ["Maintain body temperature", "Storing minerals and lipids", "Transporting oxygen and nutrients", "Facilitating movement and generating force"], a: 3, hint: "الوظيفة الأساسية للعضلات هي تحريك الجسم." },
      { q: "Which component of the musculoskeletal system is responsible for the production of movement?", type: "mcq", options: ["Muscles", "Ligaments", "Bones", "Tendons"], a: 0, hint: "العظام توفر الهيكل، لكن العضلات هي التي تنتج الحركة." },
      { q: "The term body mechanics refers to:", type: "mcq", options: ["The ability to move freely", "The use of correct muscles to complete tasks safely and efficiently", "Exercise performed for muscle building", "The movement of body fluids"], a: 1, hint: "المصطلح يركز على 'الاستخدام الصحيح' للجسم." },
      { q: "Which nursing measure prevents DVT?", type: "mcq", options: ["Applying warm compress", "Encouraging leg exercises and ambulation", "Using high pillows under knees", "Massaging calves"], a: 1, hint: "الجلطات (DVT) تحدث بسبب ركود الدم، والحركة تمنع هذا الركود." },
      { q: "Deep vein thrombosis (DVT) is a complication of:", type: "mcq", options: ["Overexertion", "Immobility", "Dehydration", "Hyperactivity"], a: 1, hint: "قلة الحركة (Immobility) تسبب ركود الدم، مما يؤدي إلى الجلطات." },
      { q: "Orthostatic hypotension occurs due to:", type: "mcq", options: ["Sudden position change after immobility", "High blood sugar", "Dehydration", "Muscle spasm"], a: 0, hint: "يحدث هذا بسبب عدم قدرة الأوعية الدموية على الاستجابة بسرعة لتغير الوضع (مثل الوقوف فجأة)." }
    ]
  },
  fundamental_mechanics_2: {
    title: "Body Mechanics - Part 2",
    questions: [
      { q: "Pressure ulcers are most likely to occur on:", type: "mcq", options: ["Soft tissues", "Bony prominences", "Muscular areas", "Skin folds"], a: 1, hint: "الأماكن التي يكون فيها العظم قريبًا من الجلد هي الأكثر عرضة للضغط." },
      { q: "The best method to prevent pressure ulcers in immobile clients is:", type: "mcq", options: ["Massage reddened areas", "Turn the patient every 2 hours", "Keep the patient in the same position", "Use hard mattresses"], a: 1, hint: "تغيير الوضعية بانتظام هو المفتاح لتخفيف الضغط المستمر." },
      { q: "The primary goal of using correct body mechanics is to:", type: "mcq", options: ["Improve appearance", "Prevent strain and injury", "Increase muscle mass", "Speed up movement"], a: 1, hint: "الهدف هو الحفاظ على سلامتك الجسدية أثناء العمل." },
      { q: "The center of gravity in the human body is located:", type: "mcq", options: ["In the head", "At the umbilical area", "Near the pelvis", "In the feet"], a: 2, hint: "يقع مركز ثقل الجسم في منطقة الحوض تقريبًا." },
      { q: "To maintain balance during lifting, the nurse should:", type: "mcq", options: ["Keep feet close together", "Bend from the waist", "Keep feet wide apart for a broad base of support", "Twist the spine"], a: 2, hint: "قاعدة الدعم (Base of support) الواسعة تزيد من اتزانك." },
      { q: "Which principle of body mechanics helps prevent back injury?", type: "mcq", options: ["Lift with the back muscles", "Keep the load away from the body", "Bend at the knees and hips, not the waist", "Twist while lifting"], a: 2, hint: "استخدم عضلات الساقين القوية (عن طريق ثني الركبتين) بدلاً من عضلات الظهر الضعيفة." },
      { q: "When moving a heavy object, the nurse should:", type: "mcq", options: ["Push or pull rather than lift", "Lift it quickly", "Use back muscles", "Stand far from the object"], a: 0, hint: "الدفع أو السحب يستهلك طاقة أقل ويقلل الضغط على الظهر مقارنة بالرفع." },
      { q: "The base of support is:", type: "mcq", options: ["The foundation on which the body rests", "The center of gravity", "The line of gravity", "The spinal column"], a: 0, hint: "هي المساحة الموجودة بين قدميك." },
      { q: "The line of gravity should pass through:", type: "mcq", options: ["Head only", "Center of gravity and base of support", "Knees and feet", "Arms and shoulders"], a: 1, hint: "للحفاظ على التوازن، يجب أن يمر خط الجاذبية داخل قاعدة الدعم." },
      { q: "Proper body alignment means:", type: "mcq", options: ["Twisting the spine", "Placing joints in unnatural positions", "Keeping body parts in correct relation to each other", "Keeping muscles tense"], a: 2, hint: "تخيل خطًا مستقيمًا يمر بجسمك من الرأس إلى القدمين." },
      { q: "To turn a patient safely in bed, the nurse should:", type: "mcq", options: ["Keep feet together", "Stand with feet apart for balance", "Pull with arms only", "Twist the upper body"], a: 1, hint: "توسيع قاعدة الدعم (الوقوف بتباعد) يمنحك ثباتًا أفضل." },
      { q: "Immobility can cause which complication?", type: "mcq", options: ["Increased bone density", "Muscle atrophy", "Increased cardiac output", "Weight loss due to exercise"], a: 1, hint: "العضلات التي لا تُستخدم تصاب بالضمور (Atrophy)." },
      { q: "The musculoskeletal complication of immobility is:", type: "mcq", options: ["Orthostatic hypotension", "Muscle atrophy and contractures", "Urinary retention", "Constipation"], a: 1, hint: "السؤال يسأل عن مضاعفات 'الجهاز الحركي' (Musculoskeletal)." },
      { q: "Deep vein thrombosis (DVT) is a complication of:", type: "mcq", options: ["Overexertion", "Immobility", "Dehydration", "Hyperactivity"], a: 1, hint: "قلة الحركة تسبب ركود الدم في الأوردة العميقة." },
      { q: "Which nursing measure prevents deep vein thrombosis DVT?", type: "mcq", options: ["Applying warm compress", "Encouraging leg exercises and ambulation", "Using high pillows under knees", "Massaging calves"], a: 1, hint: "الحركة هي أفضل وسيلة لمنع ركود الدم." },
      { q: "Orthostatic hypotension occurs due to:", type: "mcq", options: ["Sudden position change after immobility", "High blood sugar", "Dehydration", "Muscle spasm"], a: 0, hint: "هذا هو 'هبوط الضغط الانتصابي' الذي يحدث عند الوقوف فجأة." },
      { q: "When a patient uses a cane, it should be held on the:", type: "mcq", options: ["Weak side", "Strong side", "Either side", "Side of pain"], a: 1, hint: "تُمسك العصا في الجانب القوي لتوفير قاعدة دعم أوسع وتخفيف الحمل عن الجانب الضعيف." },
      { q: "Passive range-of-motion exercises are performed by:", type: "mcq", options: ["The nurse or caregiver", "The patient independently", "The family member only", "The physiotherapist only"], a: 0, hint: "كلمة 'Passive' (سلبي) تعني أن المريض لا يبذل مجهودًا، والممرض هو الذي يحرك المفصل." },
      { q: "The first step before moving any patient is to:", type: "mcq", options: ["Gather equipment", "Assess the patient's ability to assist", "Lower side rails", "Remove linens"], a: 1, hint: "قبل أن تفعل أي شيء، يجب أن 'تقيّم' الوضع وقدرة المريض." },
      { q: "Pressure ulcers are most likely to occur on:", type: "mcq", options: ["Soft tissues", "Bony prominences", "Muscular areas", "Skin folds"], a: 1, hint: "هي الأماكن التي يبرز فيها العظم ويضغط على الجلد ضد السطح (مثل الكعبين، الظهر)." },
      { q: "The best method to prevent pressure ulcers in immobile clients is:", type: "mcq", options: ["Massage reddened areas", "Turn the patient every 2 hours", "Keep the patient in the same position", "Use hard mattresses"], a: 1, hint: "السبب هو الضغط المستمر، والعلاج هو إزالة الضغط (تغيير الوضع)." }
    ]
  },

  // ==========================================================
  // القسم الثاني: مكافحة العدوى
  // ==========================================================
  fundamental_infection_1: {
    title: "Infection Control - Part 1",
    questions: [
      { q: "The single most important way to control the spread of infection by:", type: "mcq", options: ["Disinfection and sterilization", "Covering mouth and nose when sneezing or coughing", "Through hand washing", "Wear gloves"], a: 2, hint: "هذا هو الإجراء الأبسط والأكثر فعالية لمنع انتقال الميكروبات." },
      { q: "Alcohol based hand rub can be used for hand decontamination, even if hands are visibly dirty", type: "tf", a: false, hint: "الكحول لا يعمل بفعالية في وجود الأوساخ أو المواد العضوية." },
      { q: "Transmission based precautions are used in addition to standard precautions when the patient is suspected of having organism that could be spread in ways other than in blood or body fluids", type: "tf", a: true, hint: "الاحتياطات القياسية للجميع، واحتياطات العزل (Transmission based) للحالات الخاصة." },
      { q: "Staff member who has a cold sneezes another staff member sitting nearby breathes in the organism and later develops a cold. These microorganisms were most likely carried by which mode of transmission", type: "mcq", options: ["Direct contact", "Droplet", "Airborne", "Indirect contact"], a: 1, hint: "العطس والسعال ينشر رذاذًا (Droplets) لمسافة قصيرة." },
      { q: "Symptoms of TB disease include", type: "mcq", options: ["Sore throat, cough, runny nose", "Rash, headache, diarrhea", "Cough, fever, weight loss, neight sweats", "Increased thirst, hungry, dry mouth"], a: 2, hint: "السل (TB) هو مرض جهازي يؤثر بشكل أساسي على الرئة، مسببًا سعالًا مزمنًا وفقدانًا للوزن." },
      { q: "most important aspect of hand washing is:", type: "mcq", options: ["Time", "Type of soap", "Surface tension", "friction"], a: 3, hint: "الـ 'الدعك' (Friction) هو ما يزيل الميكروبات ميكانيكيًا من على الجلد." },
      { q: "Hand washing is a single most important infection control measure. Hands should be washed with soap and water for :", type: "mcq", options: ["5-10 seconds", "10-15 seconds", "30 seconds", "1 minute"], a: 1, hint: "هذه هي المدة القياسية الموصى بها (أو غناء 'Happy Birthday' مرتين)." },
      { q: "All Employees are expected to comply with", type: "mcq", options: ["The exposure control plan", "TB control plane", "Standard precautions", "All of above"], a: 3, hint: "يجب على الموظفين الالتزام بجميع سياسات السلامة." },
      { q: "which is the most likely portal of exit for influenza virus:", type: "mcq", options: ["Skin desquamation from the feet", "Respiratory droplet expelled from the nose and mouth", "Blood from a needle stick", "Urine from bladder"], a: 1, hint: "الإنفلونزا مرض تنفسي، لذا 'يخرج' من الجهاز التنفسي." },
      { q: "Tetanus typically enters the body through contaminated wounds. this describes which link", type: "mcq", options: ["Reservoir", "Portal of exit", "Portal of entry", "Mode of transmission"], a: 2, hint: "الجرح هو 'مدخل' (Portal of entry) للميكروب إلى الجسم." },
      { q: "Administering measles vaccine most directly targets which link of chain of infection:", type: "mcq", options: ["Susceptible host", "Portal of exit", "Reservoir", "Mode of transmission"], a: 0, hint: "اللقاح يجعل 'المضيف' (Host) غير 'عرضة للإصابة' (Susceptible)." },
      { q: "an N95respirator is specifically intended to interrupt which mode of transmission", type: "mcq", options: ["Airborne transmission", "Vehicle", "Vector borne", "Direct contact"], a: 0, hint: "هذا الماسك مصمم لفلترة الجزيئات الدقيقة جدًا التي تنتقل عبر 'الهواء' (Airborne)." },
      { q: "Food borne salmonella from undercooked poultry illustrates which mode of transmission", type: "mcq", options: ["Vector borne", "Direct", "Airborne", "Vehicle borne transmission"], a: 3, hint: "الطعام الملوث يُعتبر 'مركبة' (Vehicle) لنقل العدوى." },
      { q: "which is not of six links of chain of infection:", type: "mcq", options: ["Incubation period", "Mode of transmission", "Reservoir", "Portal of exit"], a: 0, hint: "فترة الحضانة (Incubation period) هي جزء من المرض، وليست حلقة في سلسلة 'انتقال' العدوى." },
      { q: "In malaria, humans who harbor plasmodium parasites in blood and liver primarily constitute which link of chain of infection", type: "mcq", options: ["Portal of exit", "Reservoir", "Portal of entry", "Susceptible host"], a: 1, hint: "الإنسان في هذه الحالة هو 'المستودع' أو 'الخزان' (Reservoir) الذي يعيش فيه الطفيل." },
      { q: "placing a mask on patient in the waiting room primarily breaks which link", type: "mcq", options: ["Reservoir", "Susceptible host", "Portal of entry", "Portal of exit"], a: 3, hint: "الماسك يمنع الميكروبات من 'الخروج' (Portal of exit) من المريض." },
      { q: "using sterile instruments for a surgical procedure primarily disrupts which link?", type: "mcq", options: ["Portal of exit", "Reservoir", "Susceptible host", "Mode of transmission(vehicle)"], a: 3, hint: "الأدوات المعقمة تمنع 'طريقة النقل' (Mode of transmission) عبر 'مركبة' (Vehicle) ملوثة." },
      { q: "which control best targets the infectious agent link itself", type: "mcq", options: ["Sterilization of reusable medical devices", "Hand hygiene before patient contact", "Visitor screening for fever", "Patient cohorting by symptoms"], a: 0, hint: "التعقيم (Sterilization) هو الإجراء الوحيد الذي 'يقتل' الميكروب (Infectious agent) نفسه." },
      { q: "What is the primary goal of infection control in a hospital setting?", type: "mcq", options: ["To reduce paperwork for staff", "To prevent the transmission of disease", "To improve the hospital's public image", "To limit movement of staff"], a: 1, hint: "الهدف الأساسي هو 'منع انتقال' العدوى بين المرضى والعاملين." },
      { q: "The most effective method of preventing the spread of infection is:", type: "mcq", options: ["Wearing gloves", "Sterilizing equipment", "Hand hygiene", "Using antibiotics"], a: 2, hint: "غسيل الأيدي هو حجر الزاوية في مكافحة العدوى." }
    ]
  },
  fundamental_infection_2: {
    title: "Infection Control - Part 2",
    questions: [
      { q: "The process that eliminates all microorganisms, including spores, is called:", type: "mcq", options: ["Cleaning", "Disinfection", "Sterilization", "Antisepsis"], a: 2, hint: "الـ 'تعقيم' (Sterilization) هو أعلى مستوى ويقضي على كل شيء." },
      { q: "The process that destroys most pathogens but not spores is:", type: "mcq", options: ["Cleaning", "Disinfection", "Sterilization", "Sanitization"], a: 1, hint: "الـ 'تطهير' (Disinfection) أقل درجة من التعقيم ولا يقتل الأبواغ (Spores)." },
      { q: "Which of the following is considered a portal of entry for infection?", type: "mcq", options: ["Intact skin", "Mouth", "Hair", "Nails"], a: 1, hint: "الجلد السليم (Intact) هو حاجز، أما الفم فهو 'مدخل' (Portal of entry) مفتوح." },
      { q: "The chain of infection begins with:", type: "mcq", options: ["Portal of entry", "Reservoir", "Infectious agent", "Mode of transmission"], a: 2, hint: "لا يمكن أن تبدأ السلسلة بدون وجود 'ميكروب' (Infectious agent) أولاً." },
      { q: "Breaking the chain of infection at the 'mode of transmission' step can be done by:", type: "mcq", options: ["Vaccination", "Isolation precautions", "Wearing PPE and practicing hand hygiene", "Providing nutritious food"], a: 2, hint: "غسيل الأيدي وارتداء الواقيات يمنعان 'طريقة النقل' (Mode of transmission)." },
      { q: "Which type of precaution is used for all patients, regardless of diagnosis?", type: "mcq", options: ["Contact precautions", "Standard precautions", "Droplet precautions", "Airborne precautions"], a: 1, hint: "الاحتياطات 'القياسية' (Standard) هي الأساس ويتم تطبيقها على الجميع." },
      { q: "Standard precautions apply to:", type: "mcq", options: ["Blood only", "All body fluids, secretions, and excretions (except sweat)", "Only infectious patients", "Urine only"], a: 1, hint: "تطبق على 'كل' سوائل الجسم (ما عدا العرق) لأننا نفترض أن الجميع قد يكون معديًا." },
      { q: "Gloves should be changed:", type: "mcq", options: ["Every 8 hours", "Between each patient", "Once soiled or damaged", "B and C"], a: 3, hint: "يجب تغيير القفازات بين كل مريض، وأيضًا إذا اتسخت أو تمزقت." },
      { q: "A nurse should perform hand hygiene:", type: "mcq", options: ["Before patient contact", "After removing gloves", "After contact with patient surroundings", "All of the above"], a: 3, hint: "هذه هي اللحظات الخمس لغسيل الأيدي (5 Moments of Hand Hygiene)." },
      { q: "Alcohol-based hand rub is ineffective against:", type: "mcq", options: ["Influenza virus", "COVID-19 virus", "Clostridium difficile spores", "Staphylococcus aureus"], a: 2, hint: "الكحول لا يقتل الأبواغ (Spores). هذه البكتيريا تتطلب غسيلًا بالماء والصابون لإزالتها." },
      { q: "A nurse should wash hands with soap and water when:", type: "mcq", options: ["Hands are visibly soiled", "After using alcohol rub", "After removing mask", "Before putting on gloves"], a: 0, hint: "إذا كانت الأيدي 'متسخة ظاهريًا' (Visibly soiled)، فالماء والصابون ضروري." },
      { q: "The most common healthcare-associated infection (HAI) is:", type: "mcq", options: ["Surgical site infection", "Urinary tract infection (UTI)", "Pneumonia", "Bloodstream infection"], a: 1, hint: "غالبًا ما تكون مرتبطة بالقساطر البولية (CAUTI)." },
      { q: "The 'reservoir' in the chain of infection refers to:", type: "mcq", options: ["Mode of transmission", "Site where microorganisms live and multiply", "Portal of exit", "Host defense"], a: 1, hint: "هو 'الخزان' أو 'المستودع' الذي يعيش فيه الميكروب (مثل الإنسان، الحيوان، الماء)." },
      { q: "Transmission through droplets (>5 microns) occurs during:", type: "mcq", options: ["Coughing and sneezing", "Skin-to-skin contact", "Vector bites", "Contaminated food"], a: 0, hint: "العطس والسعال يطلق 'الرذاذ' (Droplets) المحمل بالميكروبات." },
      { q: "Airborne precautions are used for diseases such as:", type: "mcq", options: ["Tuberculosis", "Influenza", "Norovirus", "MRSA"], a: 0, hint: "السل (TB) ينتقل عبر جزيئات 'الهواء' (Airborne) الدقيقة جدًا." },
      { q: "The N95 respirator mask is required for:", type: "mcq", options: ["Droplet precautions", "Airborne precautions", "Contact precautions", "Standard precautions"], a: 1, hint: "هذا الماسك مصمم لفلترة الميكروبات التي تنتقل عبر 'الهواء' (Airborne)." },
      { q: "Isolation precautions should be removed:", type: "mcq", options: ["When infection resolves or per policy", "After discharge", "When family requests", "Never"], a: 0, hint: "يتم إيقاف العزل بناءً على الحالة الطبية للمريض وسياسة المستشفى." },
      { q: "A patient with influenza should be placed under:", type: "mcq", options: ["Airborne precautions", "Contact precautions", "Droplet precautions", "Standard precautions only"], a: 2, hint: "الإنفلونزا تنتقل عن طريق 'الرذاذ' (Droplets) الناتج عن العطس والسعال." },
      { q: "The most important factor in preventing catheter-associated UTI (CAUTI) is:", type: "mcq", options: ["Frequent irrigation", "Using sterile technique during insertion", "Changing catheters daily", "Using larger catheters"], a: 1, hint: "الأساس هو 'التعقيم' (Sterile technique) أثناء 'التركيب' (Insertion)." },
      { q: "Surgical asepsis means:", type: "mcq", options: ["Reducing microorganisms", "Eliminating all microorganisms and spores", "Using gloves only", "Maintaining standard precautions"], a: 1, hint: "التعقيم 'الجراحي' (Surgical asepsis) يعني بيئة 'خالية تمامًا' من الميكروبات والأبواغ." }
    ]
  },
  fundamental_infection_3: {
    title: "Infection Control - Part 3",
    questions: [
      { q: "A sterile field becomes contaminated if:", type: "mcq", options: ["You turn your back on it", "It remains dry", "It is below waist level", "Both A and C"], a: 3, hint: "القاعدة هي: لا تدير ظهرك للسطح المعقم، واجعله دائمًا فوق مستوى الخصر." },
      { q: "Hand hygiene should be performed before:", type: "mcq", options: ["Donning gloves", "Eating", "Invasive procedures", "All of the above"], a: 3, hint: "غسيل الأيدي ضروري في كل هذه الحالات." },
      { q: "In which situation are contact precautions necessary?", type: "mcq", options: ["Patient with chickenpox", "Patient with MRSA wound infection", "Patient with tuberculosis", "Patient with measles"], a: 1, hint: "الـ MRSA تنتقل عن طريق 'التلامس' (Contact) المباشر مع الجرح أو الأسطح الملوثة." },
      { q: "A nurse accidentally touches a contaminated surface and then touches a patient. This is:", type: "mcq", options: ["Direct transmission", "Indirect transmission", "Airborne transmission", "Vector-borne transmission"], a: 1, hint: "النقل 'غير المباشر' (Indirect) يحدث عبر وسيط (في هذه الحالة، يد الممرض)." },
      { q: "A vector-borne disease is transmitted by:", type: "mcq", options: ["Air", "Insects", "Water", "Direct contact"], a: 1, hint: "الـ 'ناقل' (Vector) هو كائن حي (مثل الحشرات) ينقل المرض." },
      { q: "Disinfection is appropriate for:", type: "mcq", options: ["Surgical instruments", "Reusable bedpans and thermometers", "Needles", "Catheters"], a: 1, hint: "الأدوات الجراحية تحتاج تعقيم (Sterilization)، أما الأدوات الأقل خطورة فتحتاج تطهير (Disinfection)." },
      { q: "The nurse should never recap a used needle because:", type: "mcq", options: ["It wastes time", "It may cause a needle-stick injury", "It contaminates the syringe", "It damages the needle"], a: 1, hint: "إعادة تغطية الإبرة هي السبب الأول لإصابات الوخز (Needle-stick)." },
      { q: "Contaminated sharps should be disposed of:", type: "mcq", options: ["In the regular trash", "In a labeled, puncture-proof container", "In plastic bags", "After disinfection"], a: 1, hint: "يجب التخلص منها في 'صندوق الأمان' (Sharps container) المخصص." },
      { q: "The primary purpose of infection control programs is to:", type: "mcq", options: ["Reduce costs", "Prevent hospital-acquired infections", "Train new staff", "Monitor antibiotic use"], a: 1, hint: "الهدف هو منع 'العدوى المكتسبة من المستشفيات' (HAIs)." },
      { q: "Which is a symptom of a local infection?", type: "mcq", options: ["Fever", "Malaise", "Redness and swelling at site", "Chills"], a: 2, hint: "الأعراض 'الموضعية' (Local) تظهر في 'مكان' (Site) العدوى." },
      { q: "Which is a sign of a systemic infection?", type: "mcq", options: ["Redness at wound site", "Fever and malaise", "Drainage", "Swelling"], a: 0, hint: "الأعراض 'الجهازية' (Systemic) تؤثر على الجسم كله، مثل الحمى." },
      { q: "Which patient action breaks the chain of infection at the portal of exit?", type: "mcq", options: ["Covering mouth when coughing", "Using tissue improperly", "Touching open wound", "Eating with unwashed hands"], a: 0, hint: "تغطية الفم تمنع الميكروب من 'الخروج' (Portal of exit)." },
      { q: "The most frequent site of healthcare-associated infections is:", type: "mcq", options: ["Urinary tract", "Surgical wound", "Respiratory tract", "Bloodstream"], a: 0, hint: "الجهاز البولي هو الأكثر شيوعًا، وغالبًا بسبب القساطر." },
      { q: "Which of the following is an airborne infection?", type: "mcq", options: ["Tuberculosis", "MRSA", "Hepatitis B", "Influenza"], a: 0, hint: "السل (TB) هو المثال الكلاسيكي للعدوى 'المنقولة بالهواء' (Airborne)." },
      { q: "After removing PPE, the final step is to:", type: "mcq", options: ["Wash hands", "Put on gloves again", "Remove uniform", "Leave the room immediately"], a: 0, hint: "الخطوة الأخيرة 'دائمًا' بعد خلع معدات الوقاية هي غسيل الأيدي." },
      { q: "The best way to minimize cross-infection from stethoscopes is:", type: "mcq", options: ["Use personal stethoscopes only", "Wipe with alcohol after each patient use", "Disinfect weekly", "Avoid using stethoscopes"], a: 1, hint: "يجب مسح السماعة بالكحول 'بين كل مريض'." },
      { q: "The nurse uses aseptic technique primarily to:", type: "mcq", options: ["Control bleeding", "Prevent contamination and infection during invasive procedures", "Reduce pain", "Increase healing"], a: 1, hint: "الـ 'Aseptic' (الخالي من الميكروبات) يهدف إلى 'منع التلوث' (Prevent contamination)." }
    ]
  },

  // ==========================================================
  // القسم الثالث: الوقاية والفوارق الصحية
  // ==========================================================
  fundamental_prevention_1: {
    title: "Prevention & Disparities - Part 1",
    questions: [
      { q: "Which is the following is example of primary prevention", type: "mcq", options: ["Free Bp screening", "Health teaching on proper aerobic exercises", "Cancer treatment", "Post stroke rehabilitation"], a: 1, hint: "الوقاية 'الأولية' (Primary) تهدف 'لمنع' المرض قبل حدوثه، مثل التثقيف الصحي." },
      { q: "This level of prevention that include rehabilitation", type: "mcq", options: ["Primary", "Secondary", "Tertiary"], a: 2, hint: "الوقاية من 'الدرجة الثالثة' (Tertiary) تركز على 'إعادة التأهيل' (Rehabilitation) بعد المرض." },
      { q: "The nurse is explaining mammography screening to a patient who is reluctant to have the diagnostic test. what level of prevention does this diagnostic test reflect:", type: "mcq", options: ["Secondary", "Tertiary", "Primary", "Quaternary"], a: 0, hint: "الوقاية 'الثانوية' (Secondary) تهدف 'للكشف المبكر' (Screening) عن المرض." },
      { q: "A patient with an infection receives medical intervention and nursing care in a hospital setting, which level of health care services has been provided", type: "mcq", options: ["Quaternart", "Secondary", "Tertiary", "Primary"], a: 1, hint: "العلاج داخل المستشفى (Hospital setting) يُعتبر رعاية 'ثانوية' (Secondary)." },
      { q: "which intervention is an example of primary prevention", type: "mcq", options: ["administering digoxin to a patient with heart failure", "administering MMR immunization to an infant", "obtain pap smear to screen cervical cancer", "using occupational therapy to help patient cope with arthritis"], a: 1, hint: "الوقاية 'الأولية' (Primary) تمنع المرض. 'التطعيم' (Immunization) هو أفضل مثال." },
      { q: "A nurse volunteered to give influenza injections at local area. What level of care", type: "mcq", options: ["tertiary", "secondary", "primary", "promotive"], a: 2, hint: "التطعيمات (Injections) هي وقاية 'أولية' (Primary) لمنع حدوث المرض." },
      { q: "Physical therapy after stroke is an example of the", type: "mcq", options: ["Primary", "Secondary", "Tertiary"], a: 2, hint: "العلاج الطبيعي بعد الإصابة هو 'إعادة تأهيل' (Rehabilitation)، وهذا وقاية من 'الدرجة الثالثة' (Tertiary)." },
      { q: "A nurse teaching a client how to irrigate a new colostomy is providing what level of preventive care?", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Health promotion"], a: 2, hint: "تعليم المريض كيفية التعايش مع حالة مزمنة (Colostomy) هو وقاية من 'الدرجة الثالثة' (Tertiary)." },
      { q: "Which of the following is a primary prevention example?", type: "mcq", options: ["Vaccination", "Rehabilitation", "Physical therapy", "Blood pressure screening"], a: 0, hint: "الـ 'تطعيم' (Vaccination) هو وقاية 'أولية' (Primary) لمنع المرض." },
      { q: "Secondary prevention focuses on:", type: "mcq", options: ["Promoting overall wellness", "Detecting disease early", "Preventing disability", "Rehabilitation"], a: 1, hint: "الوقاية 'الثانوية' (Secondary) تركز على 'الاكتشاف المبكر' (Early detection)." },
      { q: "Tertiary prevention aims to:", type: "mcq", options: ["Prevent disease onset", "Reverse disease symptoms", "Limit disability and restore function", "Provide health education"], a: 2, hint: "الوقاية من 'الدرجة الثالثة' (Tertiary) تهدف لتقليل 'العجز' (Disability) وإعادة التأهيل." },
      { q: "Which factor is most influential in determining health disparities?", type: "mcq", options: ["Genetics", "Socioeconomic status", "Age", "Personality"], a: 1, hint: "'الوضع الاجتماعي والاقتصادي' (Socioeconomic) هو المحدد الأكبر للفوارق الصحية." },
      { q: "The leading cause of health disparities is:", type: "mcq", options: ["Smoking", "Poverty", "Education", "Lifestyle"], a: 1, hint: "الـ 'فقر' (Poverty) هو السبب الجذري لمعظم الفوارق الصحية." },
      { q: "Health disparities are defined as:", type: "mcq", options: ["Random differences in health outcomes", "Preventable differences in health among groups", "Differences caused by genetics", "Irreversible inequalities"], a: 1, hint: "الفوارق الصحية هي اختلافات 'يمكن تجنبها' (Preventable) وغير عادلة." },
      { q: "The greatest predictor of poor health outcomes is:", type: "mcq", options: ["Race", "Socioeconomic inequality", "Gender", "Age"], a: 1, hint: "'عدم المساواة الاجتماعية والاقتصادية' (Socioeconomic inequality) هو المؤشر الأقوى." },
      { q: "Which of the following is a social determinant of health?", type: "mcq", options: ["Weather", "Employment status", "Genetic disease", "Blood type"], a: 1, hint: "'المحددات الاجتماعية' (Social determinant) تشمل 'الحالة الوظيفية' (Employment)." },
      { q: "Health equity means:", type: "mcq", options: ["Everyone has the same health outcomes", "Everyone has a fair opportunity to achieve optimal health", "No one experiences disease", "Government provides free care"], a: 1, hint: "'العدالة' (Equity) تعني إعطاء الجميع 'فرصة عادلة' (Fair opportunity)." },
      { q: "Which statement about health disparity is true?", type: "mcq", options: ["It is always caused by genetics", "It reflects unequal access to resources", "It is unchangeable", "It is unrelated to environment"], a: 1, hint: "الفوارق الصحية تعكس 'عدم تكافؤ الفرص' في الوصول للموارد." },
      { q: "The goal of Healthy People 2030 is to:", type: "mcq", options: ["Eliminate infectious diseases", "Improve hospital quality", "Promote health equity and well-being for all", "Reduce nursing shortages"], a: 2, hint: "الهدف دائمًا هو 'تعزيز العدالة الصحية' (Promote health equity) للجميع." },
      { q: "Which population is most vulnerable to health disparities?", type: "mcq", options: ["Middle-aged adults", "Racial and ethnic minorities", "Urban professionals", "College students"], a: 1, hint: "'الأقليات العرقية' (Racial minorities) هي من أكثر الفئات عرضة للفوارق الصحية." }
    ]
  },
  fundamental_prevention_2: {
    title: "Prevention & Disparities - Part 2",
    questions: [
      { q: "Which is an example of secondary prevention?", type: "mcq", options: ["Health education", "Screening for hypertension", "Cardiac rehabilitation", "Immunization"], a: 1, hint: "'الفحص' (Screening) هو دائمًا وقاية 'ثانوية' (Secondary)." },
      { q: "Rehabilitation after a stroke is an example of:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Quaternary prevention"], a: 2, hint: "'إعادة التأهيل' (Rehabilitation) هي دائمًا وقاية من 'الدرجة الثالثة' (Tertiary)." },
      { q: "A nurse organizing an exercise class is practicing:", type: "mcq", options: ["Health restoration", "Health promotion", "Health protection", "Secondary prevention"], a: 1, hint: "تنظيم فصل للتمارين هو 'تعزيز للصحة' (Health promotion)." },
      { q: "The nurse's primary role in reducing health disparities is to:", type: "mcq", options: ["Provide culturally competent care", "Ignore socioeconomic differences", "Focus on acute care", "Avoid patient education"], a: 0, hint: "تقديم 'رعاية تتناسب ثقافيًا' (Culturally competent care) هو دور أساسي لتقليل الفوارق." },
      { q: "Which level of prevention is most cost-effective?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "All are equal"], a: 0, hint: "الوقاية 'الأولية' (Primary) (مثل التطعيم) هي الأقل تكلفة والأكثر فعالية." },
      { q: "A client recovering from hip surgery attends physical therapy. This is:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Quaternary prevention"], a: 2, hint: "العلاج الطبيعي بعد الجراحة هو 'إعادة تأهيل' (Tertiary)." },
      { q: "Socioeconomic status affects health because it influences:", type: "mcq", options: ["Disease classification", "Access to care and healthy resources", "Personality type", "Genetic disorders"], a: 1, hint: "الوضع الاجتماعي يؤثر على 'الوصول للرعاية' (Access to care) والموارد الصحية." },
      { q: "Health inequities are:", type: "mcq", options: ["Random differences", "Avoidable and unjust health differences", "Unchangeable disparities", "Naturally occurring inequalities"], a: 1, hint: "الـ 'Inequities' (الإجحاف) هي فوارق 'غير عادلة' (Unjust) و'يمكن تجنبها' (Avoidable)." },
      { q: "Environmental justice ensures:", type: "mcq", options: ["Urban areas get more funding", "Equal protection from environmental hazards", "Wealthy communities get cleaner air", "Rural areas are ignored"], a: 1, hint: "العدالة البيئية تعني 'حماية متساوية' (Equal protection) للجميع من الأخطار." },
      { q: "Which ethical principle guides equity in care?", type: "mcq", options: ["Beneficence", "Justice", "Autonomy", "Fidelity"], a: 1, hint: "مبدأ 'العدالة' (Justice) هو الذي يحكم 'الإنصاف' (Equity) في توزيع الرعاية." },
      { q: "Which social factor most affects infant mortality rates?", type: "mcq", options: ["Religion", "Parental education and income", "Gender", "Genetics"], a: 1, hint: "'تعليم ودخل الوالدين' هما من أقوى المحددات الاجتماعية." },
      { q: "Which group often experiences limited access to preventive services?", type: "mcq", options: ["Wealthy urban residents", "Rural communities", "Insured adults", "Health professionals"], a: 1, hint: "'المجتمعات الريفية' (Rural) غالبًا ما تعاني من نقص في الوصول للخدمات." },
      { q: "Nurses address health disparities by:", type: "mcq", options: ["Avoiding advocacy", "Promoting equitable care for all patients", "Focusing only on treatment", "Ignoring social context"], a: 1, hint: "دور الممرض هو 'تعزيز الرعاية المنصفة' (Equitable care) للجميع." },
      { q: "An example of health promotion activity is:", type: "mcq", options: ["Cancer screening", "Diet and exercise education", "Post-surgery rehabilitation", "Insulin therapy"], a: 1, hint: "'التثقيف' (Education) حول النظام الغذائي هو 'تعزيز للصحة' (Health promotion)." },
      { q: "Which level of prevention applies to cholesterol screening?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], a: 1, hint: "'الفحص' (Screening) هو دائمًا وقاية 'ثانوية' (Secondary)." },
      { q: "A nurse teaching smoking cessation addresses which prevention level?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "Emergency"], a: 0, hint: "التوعية 'للإقلاع عن التدخين' (Smoking cessation) هي وقاية 'أولية' (Primary)." },
      { q: "The nurse screening migrant workers for tuberculosis is practicing:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Health restoration"], a: 1, hint: "'الفحص' (Screening) للسل هو وقاية 'ثانوية' (Secondary)." }
    ]
  },

  // ==========================================================
  // القسم الرابع: مفاهيم الصحة والمرض
  // ==========================================================
  fundamental_concepts_1: {
    title: "Health Concepts - Part 1",
    questions: [
      { q: "Which organization defines health as complete physical, mental and social wellbeing?", type: "mcq", options: ["Unicef", "World health organization", "Organization of Islamic cooperation"], a: 1, hint: "هذا هو التعريف الأشهر للصحة، ويأتي من منظمة 'الصحة العالمية' (WHO)." },
      { q: "Mental wellbeing means:", type: "mcq", options: ["Overthinking to change what is done in the past", "Have positive thoughts and feelings", "Your body is not affected by physical disease"], a: 1, hint: "الصحة النفسية ترتبط بـ 'الأفكار والمشاعر الإيجابية'." },
      { q: "Which one is not included in dimensions of health", type: "mcq", options: ["Emotional", "Physical", "Political", "Mental", "Social"], a: 2, hint: "أبعاد الصحة تشمل الجوانب الشخصية والاجتماعية، وليس 'السياسية'." },
      { q: "Chronic disease can last less than 6 months", type: "tf", a: false, hint: "المرض 'المزمن' (Chronic) يستمر 'أكثر' من 6 أشهر." },
      { q: "What is the narrowest interpretation of health according to clinical model?", type: "mcq", options: ["Absence of disease or illness", "Ability to fulfill societal roles", "The presence of optimal health", "The state of physical and mental balance"], a: 0, hint: "النموذج 'الإكلينيكي' (Clinical) يركز فقط على 'غياب المرض'." },
      { q: "Which of the following is an example of internal factor affecting health", type: "mcq", options: ["Cultural background", "Gender", "Socioeconomic status", "Family practices"], a: 1, hint: "العوامل 'الداخلية' (Internal) هي التي نولد بها ولا يمكن تغييرها، مثل 'الجنس' (Gender)." },
      { q: "This illness classification is known to be long term or more than 6 months and signs and sympoms gradually appear", type: "mcq", options: ["Chronic", "Acute", "Hereditary", "Congenital"], a: 0, hint: "المرض 'المزمن' (Chronic) هو الذي يستمر لفترة طويلة (أكثر من 6 أشهر)." },
      { q: "Which of the following is first stage of illness behavior", type: "mcq", options: ["Symptom experience", "Hospital admission", "Recovery and rehabilitation", "Contacting medical care"], a: 0, hint: "سلوك المرض يبدأ دائمًا بـ 'الشعور بالأعراض' (Symptom experience)." },
      { q: "This is characterized by severe symptoms relatively with short duration", type: "mcq", options: ["Chronic", "Acute", "pain", "syndrome"], a: 1, hint: "المرض 'الحاد' (Acute) يكون شديدًا ولكنه 'قصير المدة'." },
      { q: "The categories of illness include communicable and non-communicable diseases", type: "tf", a: true, hint: "تنقسم الأمراض إلى 'معدية' (Communicable) و'غير معدية' (Non-communicable)." },
      { q: "A nurse follow the guidelines for a healthy lifestyle, how can this promote health in others?", type: "mcq", options: ["Be being a role model for healthy behaviors", "By not requiring suck days from work", "By never exposing others to any type of illness", "By spending less time on food"], a: 0, hint: "عندما تكون 'قدوة' (Role model)، فإنك تلهم الآخرين." },
      { q: "The agent host environment model of health and illness is based on what concept", type: "mcq", options: ["Risk factors", "Infectious diseases", "Behaviors to promote health", "stages of illness"], a: 1, hint: "هذا النموذج (العائل، الميكروب، البيئة) هو النموذج الكلاسيكي لـ 'الأمراض المعدية'." },
      { q: "which of the following is not part of chronic illness", type: "mcq", options: [". permanent changes in body structure of function", "self-treatment that relives symptoms", "o long periods of treatment and care", "often has remissions and exacerbations"], a: 1, hint: "المرض 'المزمن' (Chronic) غالبًا ما يتطلب رعاية طبية مستمرة، وليس 'علاجًا ذاتيًا' بسيطًا." },
      { q: "when providing health promotion classes, a nurse uses concepts from models of health. What do health illness continuum demonstrates", type: "mcq", options: ["illness as a fixed point of time", "the importance of family", "o wellness as a passive state", "o health as a constantly changing state"], a: 3, hint: "الـ 'Continuum' (المتصل) يوضح أن الصحة هي 'حالة متغيرة باستمرار'." },
      { q: "The agent host environment model of health views health as a constantly changing state, with high level of wellness and death being on opposite ends of scale", type: "tf", a: false, hint: "هذا وصف نموذج 'Health-Illness Continuum'، وليس نموذج (Agent-Host-Environment)." },
      { q: "Diet, exercise and weight loss are three examples of primary health promotion", type: "tf", a: true, hint: "هذه الأنشطة هي 'تعزيز للصحة' (Health promotion) وتندرج تحت الوقاية الأولية." },
      { q: "Disparity is the higher incidence of diabetes in the African American and Hispanic populations compared to white population", type: "tf", a: true, hint: "الـ 'Disparity' (الفارق) هو اختلاف في معدلات المرض بين مجموعات مختلفة." },
      { q: "In the context of health models, disease is best described as", type: "mcq", options: ["Subjective experience of feeling unwell or in pain", "An objective medically diagnosable condition with specific pathology", "The response of a person to change in their body functions", "A condition influenced primarily by social and cultural factors"], a: 1, hint: "الـ 'Disease' (المرض) هو التشخيص 'الموضوعي' (Objective)، بينما الـ 'Illness' هو الشعور 'الذاتي' (Subjective)." },
      { q: "which is an example of an acute illness?", type: "mcq", options: ["A-Diabetes", "B. Rheumatoid arthritis", "C. Pneumonia", "D. Osteoporosis"], a: 2, hint: "الالتهاب الرئوي (Pneumonia) هو مرض 'حاد' (Acute)، بينما الباقي أمراض 'مزمنة' (Chronic)." },
      { q: "A nurse provides immunization to children and adults through the public health department. Which type of health care is the nurse providing?", type: "mcq", options: ["Primary", "Secondary", "Teriatry", "Continuing care"], a: 0, hint: "التطعيمات (Immunization) هي رعاية 'أولية' (Primary)." }
    ]
  },
  fundamental_concepts_2: {
    title: "Health Concepts - Part 2",
    questions: [
      { q: "A nurse working in a community hospital's emergency department provides care to a patient having chest pain. Which level of care is the nurse providing?", type: "mcq", options: ["Primary", "Secondary", "restorative", "Continuing care"], a: 1, hint: "الرعاية في 'الطوارئ' (Emergency) والمستشفيات هي رعاية 'ثانوية' (Secondary)." },
      { q: "A nurse is preparing a presentation on health and wellness. Which statement best defines wellness?", type: "mcq", options: ["Wellness is the absence of disease.", "Wellness is a state of psychological and physiological harmony.", "Wellness is a passive state in which one is not experiencing symptoms of illness.", "Wellness is a state of optimal physical, mental, and social well-being, not merely the absence of disease."], a: 3, hint: "الـ 'Wellness' (العافية) هي تعريف شامل يتجاوز مجرد 'غياب المرض'." },
      { q: "According to the WHO, which of the following is the single most important determinant of good health or ill health?", type: "mcq", options: ["Economic conditions", "Social conditions", "Physical environment", "Genetic factors"], a: 1, hint: "العوامل 'الاجتماعية' (Social conditions) لها التأثير الأكبر على الصحة." },
      { q: "The main goal of a health care delivery system is to:", type: "mcq", options: ["Cure diseases only", "Promote, maintain, and restore health", "Provide free hospital services", "Focus on tertiary care only"], a: 1, hint: "الهدف يشمل 'تعزيز' الصحة، 'الحفاظ' عليها، و'استعادتها'." },
      { q: "Which of the following is an example of primary level of health care?", type: "mcq", options: ["Rehabilitation center", "District hospital", "Barangay health station or community clinic", "Regional medical center"], a: 2, hint: "الرعاية 'الأولية' (Primary) تحدث في 'العيادات المجتمعية' (Community clinic)." },
      { q: "Which nurse role focuses on helping clients to adopt healthy behaviors", type: "mcq", options: ["Advocate", "Educator", "Manager", "Researcher"], a: 1, hint: "الممرض كـ 'معلم' (Educator) هو الذي يساعد المرضى على تبني سلوكيات صحية." },
      { q: "The nurse acts as a client advocate when:", type: "mcq", options: ["Performing a nursing procedure skillfully", "Providing health education", "Speaking up for the client's rights and needs", "Following a physician's order exactly"], a: 2, hint: "الـ 'المدافع' (Advocate) هو الذي 'يتحدث بالنيابة عن' حقوق المريض." },
      { q: "A nurse assigned as a community health nurse primarily focuses on:", type: "mcq", options: ["Individual care in hospitals", "Family and community health promotion", "Laboratory diagnosis", "Intensive care nursing"], a: 1, hint: "ممرض 'صحة المجتمع' (Community health) يركز على 'المجتمع' ككل." },
      { q: "Which of the following health services belongs to secondary level of care?", type: "mcq", options: ["Immunization program", "Health education in schools", "Hospital care by a specialist", "Rehabilitation of stroke patients"], a: 2, hint: "الرعاية 'الثانوية' (Secondary) تشمل 'الرعاية التخصصية' (Specialist) في المستشفيات." },
      { q: "In the health team, the nurse's role as a collaborator means:", type: "mcq", options: ["Giving independent nursing care", "Working together with other professionals to provide quality care", "Supervising the work of doctors", "Conducting research independently"], a: 1, hint: "الـ 'المتعاون' (Collaborator) هو الذي 'يعمل مع' الآخرين." },
      { q: "Health promotion focuses on:", type: "mcq", options: ["Early diagnosis and treatment", "Rehabilitation", "Enhancing well-being and preventing illness", "Hospital confinement"], a: 2, hint: "'تعزيز الصحة' (Health promotion) يركز على 'الوقاية' و 'تعزيز العافية'." },
      { q: "According to the World Health Organization (WHO), health is:", type: "mcq", options: ["Absence of disease", "Ability to perform daily tasks", "Complete physical, mental, and social well-being", "Proper body functioning"], a: 2, hint: "هذا هو التعريف الأشهر لـ WHO: حالة 'كاملة' من العافية." },
      { q: "Illness can best be defined as:", type: "mcq", options: ["A physiological deviation from normal", "A subjective experience of feeling unwell", "An infectious condition", "Absence of wellness"], a: 1, hint: "الـ 'Illness' هو 'الشعور الذاتي' (Subjective experience) بالمرض." },
      { q: "Which of the following describes chronic illness?", type: "mcq", options: ["Develops quickly and resolves quickly", "Has no long-term impact", "Persists longer than six months and affects functioning", "Can be cured with medication"], a: 2, hint: "المرض 'المزمن' (Chronic) يستمر 'أكثر من 6 أشهر'." },
      { q: "The health-illness continuum shows that:", type: "mcq", options: ["Health and illness are static states", "Individuals move between levels of wellness and illness", "Illness cannot be reversed", "Health is determined only by biology"], a: 1, hint: "الـ 'Continuum' (المتصل) يوضح أن الصحة 'تتحرك' وتتغير باستمرار." },
      { q: "A patient with diabetes who maintains blood sugar through diet and exercise demonstrates:", type: "mcq", options: ["Poor coping", "High-level wellness", "Acute illness", "Low adaptation"], a: 1, hint: "حتى مع وجود مرض مزمن، يمكن تحقيق 'مستوى عالٍ من العافية' (High-level wellness)." },
      { q: "The primary focus of health promotion is to:", type: "mcq", options: ["Treat diseases early", "Prevent complications", "Encourage individuals to improve control over their health", "Cure chronic illnesses"], a: 2, hint: "'تعزيز الصحة' (Health promotion) يهدف لتمكين الأفراد من 'التحكم' في صحتهم." },
      { q: "The Health Belief Model suggests people act based on:", type: "mcq", options: ["Peer influence", "Perceived susceptibility and benefits", "Fear of hospitals", "Family history"], a: 1, hint: "النموذج يعتمد على 'تصور' الشخص لخطورة المرض و'فوائد' اتخاذ الإجراء." }
    ]
  },
  fundamental_concepts_3: {
    title: "Health Concepts - Part 3",
    questions: [
      { q: "Which factor most affects adherence to treatment?", type: "mcq", options: ["Medication cost", "Patient's belief in effectiveness", "Frequency of treatment", "Physician's reputation"], a: 1, hint: "'إيمان المريض' (Belief) بفعالية العلاج هو العامل الأهم للالتزام به." },
      { q: "100. Spirituality in health care involves:", type: "mcq", options: ["Following religious rituals only", "Seeking life meaning and connection", "Avoiding cultural discussion", "Ignoring beliefs"], a: 1, hint: "'الروحانية' (Spirituality) هي مفهوم أوسع من الدين، يتعلق بـ 'البحث عن المعنى'." },
      { q: "101. Which of the following is NOT a determinant of health?", type: "mcq", options: ["Genetics", "Health services", "Weather patterns", "Social environment"], a: 2, hint: "'محددات الصحة' (Determinants) هي عوامل ثابتة مثل البيئة الاجتماعية، وليس 'أنماط الطقس' المتغيرة." },
      { q: "102. Public health nursing focuses primarily on:", type: "mcq", options: ["Individual illness care", "Population-based health promotion", "Hospital-based recovery", "Durable power of attorney"], a: 1, hint: "'الصحة العامة' (Public health) تركز على 'السكان' (Population) ككل." },
      { q: "103. Which is an example of health policy reducing disparities?", type: "mcq", options: ["Free vaccination programs", "Restricting access to clinics", "Increasing health care costs", "Cutting insurance coverage"], a: 0, hint: "'برامج التطعيم المجانية' هي سياسة صحية تقلل الفوارق." },
      { q: "126. Which of the following best defines health according to the WHO?", type: "mcq", options: ["Absence of disease", "Complete physical, mental, and social well-being", "The ability to work efficiently", "A balanced diet"], a: 1, hint: "تعريف منظمة الصحة العالمية (WHO) هو الأشمل." },
      { q: "127. According to the World Health Organization (WHO), health is:", type: "mcq", options: ["Absence of disease", "Ability to perform daily tasks", "Complete physical, mental, and social well-being", "Proper body functioning"], a: 2, hint: "مرة أخرى، التعريف يركز على الحالة 'الكاملة' (Complete) للعافية." },
      { q: "128. Illness can best be defined as:", type: "mcq", options: ["A physiological deviation from normal", "A subjective experience of feeling unwell", "An infectious condition", "Absence of wellness"], a: 1, hint: "الـ 'Illness' هو 'الشعور الذاتي' (Subjective) للشخص بالمرض." },
      { q: "129. Which of the following describes chronic illness?", type: "mcq", options: ["Develops quickly and resolves quickly", "Has no long-term impact", "Persists longer than six months and affects functioning", "Can be cured with medication"], a: 2, hint: "المرض 'المزمن' (Chronic) يستمر 'أكثر من 6 أشهر'." },
      { q: "130. The health-illness continuum shows that:", type: "mcq", options: ["Health and illness are static states", "Individuals move between levels of wellness and illness", "Illness cannot be reversed", "Health is determined only by biology"], a: 1, hint: "الـ 'Continuum' (المتصل) يوضح أن الصحة حالة 'ديناميكية' (Moving)." },
      { q: "131. The primary focus of health promotion is to:", type: "mcq", options: ["Treat diseases early", "Prevent complications", "Encourage individuals to improve control over their health", "Cure chronic illnesses"], a: 2, hint: "'تعزيز الصحة' (Health promotion) يعني تمكين الأفراد." },
      { q: "132. Which of the following is a primary prevention example?", type: "mcq", options: ["Vaccination", "Rehabilitation", "Physical therapy", "Blood pressure screening"], a: 0, hint: "'التطعيم' (Vaccination) هو المثال الأوضح للوقاية 'الأولية' (Primary)." },
      { q: "133. Secondary prevention focuses on:", type: "mcq", options: ["Promoting overall wellness", "Detecting disease early", "Preventing disability", "Rehabilitation"], a: 1, hint: "الوقاية 'الثانوية' (Secondary) تركز على 'الاكتشاف المبكر'." },
      { q: "134. Tertiary prevention aims to:", type: "mcq", options: ["Prevent disease onset", "Reverse disease symptoms", "Limit disability and restore function", "Provide health education"], a: 2, hint: "الوقاية من 'الدرجة الثالثة' (Tertiary) تركز على 'إعادة التأهيل' (Restore function)." },
      { q: "135. Which factor is most influential in determining health disparities?", type: "mcq", options: ["Genetics", "Socioeconomic status", "Age", "Personality"], a: 1, hint: "'الوضع الاجتماعي والاقتصادي' (Socioeconomic) هو المحدد الأكبر." },
      { q: "136. The leading cause of health disparities is:", type: "mcq", options: ["Smoking", "Poverty", "Education", "Lifestyle"], a: 1, hint: "'الفقر' (Poverty) هو السبب الجذري للفوارق." },
      { q: "137. Health disparities are defined as:", type: "mcq", options: ["Random differences in health outcomes", "Preventable differences in health among groups", "Differences caused by genetics", "Irreversible inequalities"], a: 1, hint: "الفوارق الصحية هي اختلافات 'يمكن تجنبها' (Preventable) وغير عادلة." },
      { q: "138. The greatest predictor of poor health outcomes is:", type: "mcq", options: ["Race", "Socioeconomic inequality", "Gender", "Age"], a: 1, hint: "'عدم المساواة الاجتماعية والاقتصادية' هو المؤشر الأقوى." },
      { q: "139. Which of the following is a social determinant of health?", type: "mcq", options: ["Weather", "Employment status", "Genetic disease", "Blood type"], a: 1, hint: "'المحددات الاجتماعية' (Social determinant) تشمل 'الحالة الوظيفية'." }
    ]
  },
  fundamental_concepts_4: {
    title: "Health Concepts - Part 4",
    questions: [
      { q: "140. Health equity means:", type: "mcq", options: ["Everyone has the same health outcomes", "Everyone has a fair opportunity to achieve optimal health", "No one experiences disease", "Government provides free care"], a: 1, hint: "'العدالة' (Equity) تعني 'فرصة عادلة' (Fair opportunity)، وليس بالضرورة نتائج متساوية." },
      { q: "141. Which statement about health disparity is true?", type: "mcq", options: ["It is always caused by genetics", "It reflects unequal access to resources", "It is unchangeable", "It is unrelated to environment"], a: 1, hint: "الفوارق الصحية تعكس 'عدم تكافؤ الفرص' في الوصول للموارد." },
      { q: "150. Which is an example of secondary prevention?", type: "mcq", options: ["Health education", "Screening for hypertension", "Cardiac rehabilitation", "Immunization"], a: 1, hint: "'الفحص' (Screening) هو دائمًا وقاية 'ثانوية' (Secondary)." },
      { q: "151. Rehabilitation after a stroke is an example of:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Quaternary prevention"], a: 2, hint: "'إعادة التأهيل' (Rehabilitation) هي دائمًا وقاية من 'الدرجة الثالثة' (Tertiary)." },
      { q: "152. A nurse organizing an exercise class is practicing:", type: "mcq", options: ["Health restoration", "Health promotion", "Health protection", "Secondary prevention"], a: 1, hint: "فصل التمارين هو 'تعزيز للصحة' (Health promotion)." },
      { q: "153. The nurse's primary role in reducing health disparities is to:", type: "mcq", options: ["Provide culturally competent care", "Ignore socioeconomic differences", "Focus on acute care", "Avoid patient education"], a: 0, hint: "تقديم 'رعاية تتناسب ثقافيًا' (Culturally competent care) هو دور أساسي." },
      { q: "154. The Health Belief Model suggests people act based on:", type: "mcq", options: ["Peer influence", "Perceived susceptibility and benefits", "Fear of hospitals", "Family history"], a: 1, hint: "النموذج يعتمد على 'تصور' الشخص لخطورة المرض و'فوائد' اتخاذ الإجراء." },
      { q: "155. Which factor most affects adherence to treatment?", type: "mcq", options: ["Medication cost", "Patient's belief in effectiveness", "Frequency of treatment", "Physician's reputation"], a: 1, hint: "'إيمان المريض' (Belief) بفعالية العلاج هو العامل الأهم للالتزام به." },
      { q: "156. Which of the following is NOT a determinant of health?", type: "mcq", options: ["Genetics", "Health services", "Weather patterns", "Social environment"], a: 2, hint: "'محددات الصحة' (Determinants) هي عوامل ثابتة مثل البيئة الاجتماعية، وليس 'أنماط الطقس'." },
      { q: "157. Which is an example of health policy reducing disparities?", type: "mcq", options: ["Free vaccination programs", "Restricting access to clinics", "Increasing health care costs", "Cutting insurance coverage"], a: 0, hint: "'برامج التطعيم المجانية' هي سياسة صحية تقلل الفوارق." },
      { q: "158. Which level of prevention is most cost-effective?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "All are equal"], a: 0, hint: "الوقاية 'الأولية' (Primary) هي الأقل تكلفة والأكثر فعالية." },
      { q: "159. A client recovering from hip surgery attends physical therapy. This is:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Quaternary prevention"], a: 2, hint: "العلاج الطبيعي بعد الجراحة هو 'إعادة تأهيل' (Tertiary)." },
      { q: "160. Socioeconomic status affects health because it influences:", type: "mcq", options: ["Disease classification", "Access to care and healthy resources", "Personality type", "Genetic disorders"], a: 1, hint: "الوضع الاجتماعي يؤثر على 'الوصول للرعاية' والموارد الصحية." },
      { q: "161. Health inequities are:", type: "mcq", options: ["Random differences", "Avoidable and unjust health differences", "Unchangeable disparities", "Naturally occurring inequalities"], a: 1, hint: "الـ 'Inequities' (الإجحاف) هي فوارق 'غير عادلة' (Unjust) و'يمكن تجنبها' (Avoidable)." },
      { q: "162. Which social factor most affects infant mortality rates?", type: "mcq", options: ["Religion", "Parental education and income", "Gender", "Genetics"], a: 1, hint: "'تعليم ودخل الوالدين' هما من أقوى المحددات الاجتماعية." },
      { q: "163- An example of health promotion activity is:", type: "mcq", options: ["Cancer screening", "Diet and exercise education", "Post-surgery rehabilitation", "Insulin therapy"], a: 1, hint: "'التثقيف' (Education) حول النظام الغذائي هو 'تعزيز للصحة' (Health promotion)." },
      { q: "164. Which level of prevention applies to cholesterol screening?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], a: 1, hint: "'الفحص' (Screening) هو دائمًا وقاية 'ثانوية' (Secondary)." },
      { q: "165. A nurse teaching smoking cessation addresses which prevention level?", type: "mcq", options: ["Primary", "Secondary", "Tertiary", "Emergency"], a: 0, hint: "التوعية 'للإقلاع عن التدخين' هي وقاية 'أولية' (Primary)." },
      { q: "166. The biomedical model defines health as:", type: "mcq", options: ["Balance of physical, mental, and spiritual well-being", "Absence of disease or dysfunction", "Ability to adapt to environment", "Complete wellness"], a: 1, hint: "النموذج 'الطبي الحيوي' (Biomedical) يركز فقط على 'غياب المرض'." },
      { q: "167. Social determinants of health are:", type: "mcq", options: ["Only related to genetics", "Non-medical factors influencing health", "Random influences", "Hospital policies"], a: 1, hint: "'المحددات الاجتماعية' هي عوامل 'غير طبية' (Non-medical) تؤثر على الصحة." },
      { q: "168. The nurse screening migrant workers for tuberculosis is practicing:", type: "mcq", options: ["Primary prevention", "Secondary prevention", "Tertiary prevention", "Health restoration"], a: 1, hint: "'الفحص' (Screening) للسل هو وقاية 'ثانوية' (Secondary)." }
    ]
  }
};
