window.microbiologyData = {
  morphology: {
    title: "Bacterial Morphology",
    questions: [
      { q: "Which of the following lacks a cell wall?", type: "mcq", options: ["Mycoplasma", "Mycobacteria", "Staphylococci", "Spirochetes"], a: 0, hint: "هذه البكتيريا هي استثناء فريد وتسبب الالتهاب الرئوي اللانمطي." },
      { q: "Which of the following contains N-acetylmuramic acid?", type: "mcq", options: ["Fungi", "Protozoa", "Bacteria", "Mycoplasma"], a: 2, hint: "هذا المركب هو مكون أساسي لجدار الخلية البكتيرية (الببتيدوجلايكان)." },
      { q: "Which of the following contains dipicolinic acid?", type: "mcq", options: ["Spores", "Vegetative cells", "Capsule", "Flagella"], a: 0, hint: "هذا المركب مسؤول عن مقاومة الأبواغ للحرارة." },
      { q: "The cell wall of gram-positive bacteria consists of:", type: "mcq", options: ["Lipid A", "Thin peptidoglycan layer", "Thick peptidoglycan layer", "Outer membrane"], a: 2, hint: "هذه الطبقة السميكة هي التي تحتفظ بصبغة الكريستال البنفسجية." },
      { q: "The function of the outer membrane in gram-negative bacteria is:", type: "mcq", options: ["Protection from antibiotics", "Passage of nutrients", "Protection from bile salts", "All of the above"], a: 3, hint: "الغشاء الخارجي يوفر حاجزاً وقائياً بعدة طرق." },
      { q: "Which of the following is responsible for endotoxic activity?", type: "mcq", options: ["Lipid A", "O-antigen", "Core polysaccharide", "Peptidoglycan"], a: 0, hint: "هذا هو الجزء الدهني السام من الـ LPS (السكريات الدهنية المتعددة) في البكتيريا سالبة الجرام." },
      { q: "Which of the following is true about gram-positive bacteria?", type: "mcq", options: ["Stain red by Gram stain", "Contain teichoic acid", "Have an outer membrane", "Contain porin proteins"], a: 1, hint: "هذا الحمض مرتبط بجدار الخلية ويمنحها شحنة سالبة." },
      { q: "Which of the following is true about gram-negative bacteria?", type: "mcq", options: ["Stain purple by Gram stain", "Lack an outer membrane", "Contain endotoxin", "Have a thick peptidoglycan layer"], a: 2, hint: "الـ Endotoxin (السم الداخلي) هو جزء لا يتجزأ من الغشاء الخارجي لها." },
      { q: "Which of the following structures is essential for bacterial viability?", type: "mcq", options: ["Cell wall", "Capsule", "Flagella", "Pili"], a: 0, hint: "بدون هذا التركيب، تنفجر الخلية البكتيرية بسبب الضغط الأسموزي (باستثناء الميكوبلازما)." },
      { q: "Which of the following is a function of the cell membrane?", type: "mcq", options: ["Selective permeability", "Electron transport", "Energy production", "All of the above"], a: 3, hint: "الغشاء الخلوي هو موقع للعديد من العمليات الحيوية، يشبه وظائف الميتوكوندريا في حقيقيات النوى." },
      { q: "Which of the following is a function of pili?", type: "mcq", options: ["Motility", "Attachment", "Phagocytosis", "Energy production"], a: 1, hint: "تُعرف أيضاً باسم 'Fimbriae'، وهي تساعد البكتيريا على الالتصاق بالأسطح." },
      { q: "Which of the following is true about capsules?", type: "mcq", options: ["Polysaccharide in nature (mostly)", "Protect against phagocytosis", "Used in serological identification", "All of the above"], a: 3, hint: "الكبسولة هي عامل ضراوة (virulence factor) مهم." },
      { q: "Which of the following is true about flagella?", type: "mcq", options: ["Organ of motility", "Composed of flagellin protein", "Used for identification (H-antigen)", "All of the above"], a: 3, hint: "الأسواط لها وظائف متعددة تتجاوز مجرد الحركة." },
      { q: "Bacteria that are comma-shaped are called:", type: "mcq", options: ["Cocci", "Bacilli", "Vibrios", "Spirilla"], a: 2, hint: "مثال عليها البكتيريا المسببة للكوليرا." },
      { q: "Bacteria that form grape-like clusters are called:", type: "mcq", options: ["Streptococci", "Staphylococci", "Diplococci", "Tetrads"], a: 1, hint: "كلمة 'Staphylo' في اليونانية تعني 'عنقود'." },
      { q: "The counterstain used in Gram staining is:", type: "mcq", options: ["Crystal violet", "Iodine", "Alcohol", "Safranin"], a: 3, hint: "هذه هي الصبغة الحمراء التي تصبغ البكتيريا سالبة الجرام." },
      { q: "Acid-fast bacteria stain red with:", type: "mcq", options: ["Gram stain", "Ziehl-Neelsen stain", "Giemsa stain", "India ink"], a: 1, hint: "تستخدم هذه الصبغة لتحديد بكتيريا السل (TB) بسبب جدارها الشمعي." },
      { q: "Which structure is used for attachment to surfaces?", type: "mcq", options: ["Flagella", "Capsule", "Pili (Fimbriae)", "Spores"], a: 2, hint: "هذه التراكيب تشبه الشعر وهي أقصر من الأسواط." },
      { q: "Plasmids are:", type: "mcq", options: ["Essential for bacterial survival", "Extrachromosomal DNA", "Part of the bacterial chromosome", "Composed of RNA"], a: 1, hint: "هي قطع دائرية صغيرة من الحمض النووي تحمل جينات إضافية (مثل مقاومة المضادات الحيوية)." }
    ]
  },
  physiology: {
    title: "Bacterial Physiology",
    questions: [
      { q: "Bacteria that grow best at 37°C are called:", type: "mcq", options: ["Psychrophiles", "Mesophiles", "Thermophiles", "Hyperthermophiles"], a: 1, hint: "هذه هي درجة حرارة جسم الإنسان، وهي مثالية لمعظم البكتيريا المسببة للأمراض." },
      { q: "Bacteria that require oxygen for growth are called:", type: "mcq", options: ["Obligate anaerobes", "Facultative anaerobes", "Obligate aerobes", "Aerotolerant anaerobes"], a: 2, hint: "كلمة 'Obligate' تعني 'إجباري' أو 'ملزم'." },
      { q: "Bacteria that can grow with or without oxygen are called:", type: "mcq", options: ["Obligate anaerobes", "Facultative anaerobes", "Obligate aerobes", "Microaerophiles"], a: 1, hint: "كلمة 'Facultative' تعني 'اختياري' أو 'مرن'." },
      { q: "The phase of bacterial growth curve with maximum growth rate is:", type: "mcq", options: ["Lag phase", "Log phase", "Stationary phase", "Decline phase"], a: 1, hint: "تُعرف أيضاً بالمرحلة الأسية (Exponential Phase)." },
      { q: "The phase where bacterial growth equals death rate is:", type: "mcq", options: ["Lag phase", "Log phase", "Stationary phase", "Decline phase"], a: 2, hint: "في هذه المرحلة، تبدأ الموارد الغذائية في النضوب وتتراكم الفضلات السامة." },
      { q: "Which of these enzymes protects against toxic oxygen products?", type: "mcq", options: ["Catalase", "Superoxide dismutase", "Peroxidase", "All of the above"], a: 3, hint: "البكتيريا الهوائية تحتاج إلى آليات دفاعية ضد نواتج الأكسجين التفاعلية." },
      { q: "Most pathogenic bacteria are:", type: "mcq", options: ["Psychrophiles", "Mesophiles", "Thermophiles", "Halophiles"], a: 1, hint: "إنها تنمو بشكل أفضل في درجة حرارة الجسم المضيف (حوالي 37 درجة مئوية)." },
      { q: "Bacteria that grow best in high salt concentrations are:", type: "mcq", options: ["Acidophiles", "Alkaliphiles", "Halophiles", "Barophiles"], a: 2, hint: "كلمة 'Halo' تشير إلى الملح (مثل الهالوجينات)." },
      { q: "The process of converting N2 to NH3 is called:", type: "mcq", options: ["Nitrification", "Denitrification", "Nitrogen fixation", "Ammonification"], a: 2, hint: "هذه العملية 'تثبت' النيتروجين الجوي في شكل يمكن استخدامه." },
      { q: "Which process yields the most ATP?", type: "mcq", options: ["Aerobic respiration", "Anaerobic respiration", "Fermentation", "Glycolysis"], a: 0, hint: "هذه العملية تستخدم الأكسجين كمستقبل نهائي للإلكترونات، وهي الأكثر كفاءة." },
      { q: "Fermentation is characterized by:", type: "mcq", options: ["Using oxygen as final electron acceptor", "Using an inorganic molecule as final electron acceptor", "Using an organic molecule as final electron acceptor", "Generating 38 ATP"], a: 2, hint: "التخمر لا يستخدم سلسلة نقل الإلكترون بنفس طريقة التنفس، وينتج طاقة أقل بكثير." },
      { q: "The time required for a bacterial population to double is called:", type: "mcq", options: ["Lag time", "Generation time", "Log time", "Stationary time"], a: 1, hint: "يُعرف أيضاً بـ 'زمن التضاعف'." },
      { q: "A 'capnophile' is a bacterium that requires:", type: "mcq", options: ["High salt", "High pressure", "High CO2 levels", "Low oxygen"], a: 2, hint: "كلمة 'Capno' تشير إلى ثاني أكسيد الكربون." },
      { q: "Which of these is a trace element required by bacteria?", type: "mcq", options: ["Carbon", "Nitrogen", "Zinc", "Sulfur"], a: 2, hint: "العناصر النزرة (Trace elements) مطلوبة بكميات ضئيلة جداً، على عكس الكربون أو النيتروجين." },
      { q: "Organisms that use light as an energy source are called:", type: "mcq", options: ["Chemotrophs", "Phototrophs", "Autotrophs", "Heterotrophs"], a: 1, hint: "كلمة 'Photo' تشير إلى الضوء." },
      { q: "Organisms that use organic compounds as a carbon source are:", type: "mcq", options: ["Autotrophs", "Heterotrophs", "Lithotrophs", "Phototrophs"], a: 1, hint: "كلمة 'Hetero' تعني 'آخر' (أي يتغذى على كائنات أخرى)، بينما 'Auto' تعني 'ذاتي'." },
      { q: "The 'lag phase' is a period of:", type: "mcq", options: ["Rapid cell division", "No metabolic activity", "Adaptation and synthesis", "Cell death"], a: 2, hint: "إنها فترة 'تباطؤ' أو 'تأقلم' قبل بدء النمو السريع." },
      { q: "Which transport mechanism requires energy (ATP)?", type: "mcq", options: ["Simple diffusion", "Facilitated diffusion", "Active transport", "Osmosis"], a: 2, hint: "النقل 'النشط' يتطلب طاقة لنقل المواد ضد تدرج التركيز." },
      { q: "Facultative anaerobes primarily use... if O2 is present.", type: "mcq", options: ["Fermentation", "Aerobic respiration", "Anaerobic respiration", "Photosynthesis"], a: 1, hint: "هي تختار المسار الأكثر كفاءة (الأكثر إنتاجاً للطاقة) عند توفر الأكسجين." },
      { q: "Most bacteria grow best at a pH of:", type: "mcq", options: ["1-3", "4-5", "6.5-7.5", "9-11"], a: 2, hint: "معظم البكتيريا (خاصة الممرضة) تفضل بيئة متعادلة، تشبه بيئة الجسم." }
    ]
  },
  flora: {
    title: "Normal Flora",
    questions: [
      { q: "Normal flora is most abundant in the:", type: "mcq", options: ["Stomach", "Small intestine", "Colon", "Lungs"], a: 2, hint: "هذا الجزء من الأمعاء الغليظة يحتوي على تريليونات البكتيريا." },
      { q: "Which of the following sites is normally sterile?", type: "mcq", options: ["Skin", "Mouth", "Blood", "Vagina"], a: 2, hint: "وجود بكتيريا في هذا الموقع يعني وجود عدوى (تجرثم الدم)." },
      { q: "The predominant bacteria in the vagina of adult women are:", type: "mcq", options: ["Staphylococci", "Streptococci", "Lactobacilli", "E. coli"], a: 2, hint: "هذه البكتيريا تنتج حمض اللاكتيك، مما يحافظ على بيئة حمضية واقية." },
      { q: "Normal flora of the skin includes:", type: "mcq", options: ["Staphylococcus epidermidis", "Propionibacterium acnes", "Diphtheroids", "All of the above"], a: 3, hint: "الجلد ليس معقماً ويستضيف أنواعاً مختلفة من البكتيريا." },
      { q: "Which of the following is a benefit of normal flora?", type: "mcq", options: ["Synthesize vitamins (K, B12)", "Prevent colonization by pathogens", "Stimulate the immune system", "All of the above"], a: 3, hint: "الفلورا الطبيعية تقدم العديد من الفوائد للمضيف." },
      { q: "The most common bacteria in the mouth (dental plaque) is:", type: "mcq", options: ["Streptococcus mutans", "E. coli", "Staphylococcus aureus", "Lactobacillus"], a: 0, hint: "هذه البكتيريا هي السبب الرئيسي لتسوس الأسنان." },
      { q: "The stomach is relatively sterile due to:", type: "mcq", options: ["High pH", "Low pH (acidity)", "Presence of bile", "Lack of nutrients"], a: 1, hint: "حمض الهيدروكلوريك (HCl) يجعل البيئة شديدة الحموضة." },
      { q: "Which organism is a common cause of urinary tract infections (UTI)?", type: "mcq", options: ["Staphylococcus epidermidis", "E. coli", "Streptococcus pyogenes", "Neisseria gonorrhoeae"], a: 1, hint: "هذه البكتيريا هي جزء من الفلورا الطبيعية للأمعاء ولكنها تسبب مشاكل إذا وصلت للمثانة." },
      { q: "An 'opportunistic pathogen' is an organism that:", type: "mcq", options: ["Always causes disease", "Is part of the normal flora", "Causes disease in a compromised host", "Is transmitted by vectors"], a: 2, hint: "إنها 'تنتهاز' الفرصة عندما يضعف الجهاز المناعي للمضيف." },
      { q: "The term 'microbial antagonism' means:", type: "mcq", options: ["Normal flora helping pathogens", "Normal flora preventing pathogen growth", "Pathogens causing disease", "Microbes growing in harmony"], a: 1, hint: "الفلورا الطبيعية 'تعادي' أو 'تنافس' الميكروبات الممرضة." },
      { q: "Antibiotic therapy can lead to:", type: "mcq", options: ["Overgrowth of normal flora", "Superinfection (e.g., C. difficile)", "Increased immunity", "Sterilization of the gut"], a: 1, hint: "المضادات الحيوية واسعة المجال تقتل الفلورا الطبيعية، مما يسمح للميكروبات المقاومة (مثل C. difficile) بالنمو الزائد." },
      { q: "Organisms that are acquired temporarily and are not part of the established flora are:", type: "mcq", options: ["Resident flora", "Transient flora", "Opportunistic flora", "Pathogenic flora"], a: 1, hint: "إنها بكتيريا 'عابرة' أو 'مؤقتة' يمكن إزالتها بسهولة (مثل غسل اليدين)." },
      { q: "Which vitamin is synthesized by E. coli in the gut?", type: "mcq", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], a: 3, hint: "هذا الفيتامين ضروري لتخثر الدم." },
      { q: "The 'germ-free' (gnotobiotic) animal:", type: "mcq", options: ["Is healthier than normal animals", "Has a poorly developed immune system", "Is resistant to pathogens", "Has a normal lifespan"], a: 1, hint: "هذا يثبت أن الفلورا الطبيعية ضرورية لـ 'تدريب' جهاز المناعة." },
      { q: "Which of the following is NOT a benefit of normal flora?", type: "mcq", options: ["Bacterial interference", "Vitamin synthesis", "Causing dental caries", "Immune stimulation"], a: 2, hint: "تسوس الأسنان هو مرض، وليس فائدة." },
      { q: "The most predominant anaerobe in the colon is:", type: "mcq", options: ["E. coli", "Bacteroides fragilis", "Clostridium perfringens", "Lactobacillus"], a: 1, hint: "البكتيريا اللاهوائية تفوق الهوائية بكثير في القولون." },
      { q: "The normal flora of the upper respiratory tract (nose, pharynx) resembles:", type: "mcq", options: ["Skin flora", "Gut flora", "Mouth flora", "Vaginal flora"], a: 2, hint: "هذه المناطق متصلة ببعضها البعض." },
      { q: "Babies acquire their initial normal flora:", type: "mcq", options: ["In the uterus (sterile)", "During and after birth", "From antibiotics", "They are born with it"], a: 1, hint: "الرحم بيئة معقمة. يبدأ الاستعمار الميكروبي عند الولادة." }
    ]
  },
  sterilization: {
    title: "Sterilization & Disinfection",
    questions: [
      { q: "The complete killing or removal of all forms of life, including spores, is:", type: "mcq", options: ["Disinfection", "Sterilization", "Antisepsis", "Sanitization"], a: 1, hint: "التعقيم هو المستوى الأعلى، ويضمن القضاء التام." },
      { q: "The reduction of microbial load to a safe public health level is:", type: "mcq", options: ["Disinfection", "Sterilization", "Antisepsis", "Sanitization"], a: 3, hint: "هذا المصطلح يستخدم غالباً في خدمات الطعام (مثل غسل الأطباق)." },
      { q: "Which of the following is the most resistant to sterilization?", type: "mcq", options: ["Vegetative bacteria", "Viruses (enveloped)", "Fungal spores", "Bacterial endospores"], a: 3, hint: "الأبواغ البكتيرية مصممة للبقاء على قيد الحياة في الظروف القاسية." },
      { q: "The standard condition for autoclaving (steam under pressure) is:", type: "mcq", options: ["100°C for 30 min", "121°C for 15 min", "160°C for 2 hours", "72°C for 15 sec"], a: 1, hint: "هذه هي الحرارة والبخار (الضغط) اللازم لقتل الأبواغ." },
      { q: "Autoclaving kills by:", type: "mcq", options: ["Denaturing proteins", "Oxidation", "Alkylation", "Radiation damage"], a: 0, hint: "البخار تحت الضغط ينقل الحرارة بكفاءة، مما يؤدي إلى 'تخثر' أو 'تدمير' البروتينات." },
      { q: "Dry heat sterilization (hot air oven) requires:", type: "mcq", options: ["121°C for 15 min", "100°C for 1 hour", "160°C for 2 hours", "Lower temp than autoclaving"], a: 2, hint: "الحرارة الجافة أقل كفاءة من الحرارة الرطبة، لذا فهي تحتاج درجة حرارة أعلى ووقت أطول." },
      { q: "Pasteurization is used to:", type: "mcq", options: ["Sterilize milk", "Reduce microbial load in milk", "Kill spores in milk", "Make milk thicker"], a: 1, hint: "البسترة لا تقتل كل شيء (ليست تعقيماً)، لكنها تقتل الميكروبات الممرضة وتقلل التلف." },
      { q: "The (HTST) pasteurization method is:", type: "mcq", options: ["63°C for 30 min", "72°C for 15 sec", "140°C for 3 sec (UHT)", "100°C for 10 min"], a: 1, hint: "HTST = High Temperature Short Time (درجة حرارة عالية لوقت قصير)." },
      { q: "Which of the following is a form of ionizing radiation?", type: "mcq", options: ["UV light", "Gamma rays", "Microwaves", "Infrared"], a: 1, hint: "الأشعة المؤينة (Ionizing) أقوى بكثير من الأشعة فوق البنفسجية (غير المؤينة)." },
      { q: "Ionizing radiation (Gamma) is used to sterilize:", type: "mcq", options: ["Sutures and plastic syringes", "Surgical instruments (metal)", "Glassware", "Culture media"], a: 0, hint: "تُستخدم للمواد التي لا تتحمل الحرارة، مثل البلاستيك." },
      { q: "UV light sterilizes by:", type: "mcq", options: ["Creating hydroxyl radicals", "Causing thymine dimers in DNA", "Denaturing proteins", "Puncturing the cell wall"], a: 1, hint: "الأشعة فوق البنفسجية تدمر الحمض النووي (DNA) مباشرة." },
      { q: "UV light is limited by its:", type: "mcq", options: ["High cost", "Poor penetrating power", "Toxicity", "Flammability"], a: 1, hint: "لا يمكنها اختراق الأسطح، لذا هي مناسبة لتعقيم الأسطح والهواء فقط." },
      { q: "Filtration is used to sterilize:", type: "mcq", options: ["Heat-labile liquids (e.g., serum)", "Glassware", "Metal instruments", "Plastic tubing"], a: 0, hint: "تُستخدم للسوائل الحساسة للحرارة عن طريق 'فلترة' البكتيريا منها." },
      { q: "HEPA filters are used to remove microbes from:", type: "mcq", options: ["Liquids", "Air", "Surfaces", "Food"], a: 1, hint: "تستخدم في غرف العمليات وأنظمة السلامة البيولوجية لتنقية الهواء." },
      { q: "Which of the following is a halogen disinfectant?", type: "mcq", options: ["Alcohol", "Phenol", "Chlorine (Bleach)", "Formaldehyde"], a: 2, hint: "الهالوجينات هي عناصر المجموعة 17 (مثل الكلور واليود)." },
      { q: "70% alcohol is more effective than 95% alcohol because:", type: "mcq", options: ["It evaporates slower", "Water is needed for protein denaturation", "It penetrates better", "All of the above"], a: 3, hint: "الماء الموجود في تركيز 70% ضروري لعملية تدمير البروتينات ويساعد على الاختراق." },
      { q: "Which chemical is used for 'cold sterilization' of surgical instruments?", type: "mcq", options: ["70% Alcohol", "Iodine", "Glutaraldehyde", "Soap"], a: 2, hint: "هذا المركب قوي بما يكفي لقتل الأبواغ عند استخدامه لفترة كافية." },
      { q: "Ethylene oxide is a:", type: "mcq", options: ["Liquid disinfectant", "Gas used for sterilization", "Halogen", "Phenolic compound"], a: 1, hint: "يُستخدم كغاز لتعقيم المواد الحساسة للحرارة والرطوبة." },
      { q: "A disinfectant used on living tissue (skin) is called:", type: "mcq", options: ["Sterilant", "Disinfectant", "Antiseptic", "Sanitizer"], a: 2, hint: "كلمة 'Antiseptic' (مطهر) تستخدم للأنسجة الحية، بينما 'Disinfectant' (معقم) للأسطح." },
      { q: "Phenol coefficient is used to:", type: "mcq", options: ["Measure the effectiveness of a disinfectant", "Count bacteria", "Test for sterility", "Identify bacteria"], a: 0, hint: "هو مقياس يقارن فعالية مطهر ما بفعالية الفينول." }
    ]
  },
  chemotherapy: {
    title: "Antimicrobial Chemotherapy",
    questions: [
      { q: "Which of the following inhibits cell wall synthesis?", type: "mcq", options: ["Penicillin", "Tetracycline", "Rifampin", "Sulfonamides"], a: 0, hint: "هذه هي آلية عمل عائلة البيتا لاكتام (Beta-lactams)." },
      { q: "Penicillin's mechanism of action is inhibition of:", type: "mcq", options: ["Protein synthesis (50S)", "Protein synthesis (30S)", "Transpeptidation (cell wall)", "Nucleic acid synthesis"], a: 2, hint: "يمنع هذا الإنزيم من تكوين الروابط العرضية في جدار الخلية." },
      { q: "Which of the following targets the 30S ribosomal subunit?", type: "mcq", options: ["Tetracycline", "Erythromycin", "Chloramphenicol", "Vancomycin"], a: 0, hint: "يعمل عن طريق منع ارتباط t-RNA بالريبوسوم." },
      { q: "Which of the following targets the 50S ribosomal subunit?", type: "mcq", options: ["Gentamicin", "Erythromycin (Macrolides)", "Ciprofloxacin", "Penicillin"], a: 1, hint: "هذه العائلة (الماكروليدات) تمنع الريبوسوم من التحرك على طول mRNA." },
      { q: "Vancomycin is effective against:", type: "mcq", options: ["Gram-negative bacteria", "Gram-positive bacteria (e.g., MRSA)", "Fungi", "Viruses"], a: 1, hint: "يُستخدم كـ 'خط دفاع أخير' ضد البكتيريا موجبة الجرام المقاومة مثل MRSA." },
      { q: "Sulfonamides work by:", type: "mcq", options: ["Inhibiting cell wall synthesis", "Inhibiting protein synthesis", "Inhibiting DNA gyrase", "Inhibiting folic acid synthesis"], a: 3, hint: "تعمل كـ 'مثبط تنافسي' لإنزيم PABA، وهو ضروري لصنع حمض الفوليك." },
      { q: "Rifampin (Rifampicin) inhibits:", type: "mcq", options: ["DNA gyrase", "RNA polymerase", "Folic acid synthesis", "Protein synthesis"], a: 1, hint: "يمنع هذا الإنزيم من نسخ الحمض النووي (DNA) إلى الحمض النووي الريبي (RNA)." },
      { q: "Quinolones (e.g., Ciprofloxacin) inhibit:", type: "mcq", options: ["DNA gyrase (Topoisomerase)", "RNA polymerase", "Cell wall synthesis", "Protein synthesis"], a: 0, hint: "هذا الإنزيم ضروري لـ 'فك' التفاف الحمض النووي (DNA) أثناء التضاعف." },
      { q: "An antibiotic that is effective against a wide range of bacteria is:", type: "mcq", options: ["Narrow-spectrum", "Broad-spectrum", "Bacteriostatic", "Bactericidal"], a: 1, hint: "واسع المجال (Broad-spectrum) يعني أنه يؤثر على بكتيريا موجبة وسالبة الجرام." },
      { q: "An antibiotic that kills bacteria is:", type: "mcq", options: ["Bacteriostatic", "Bactericidal", "Antiseptic", "Disinfectant"], a: 1, hint: "كلمة 'Cidal' تعني 'قاتل'." },
      { q: "The lowest concentration of an antibiotic that inhibits visible growth is:", type: "mcq", options: ["MIC (Minimum Inhibitory Concentration)", "MBC (Minimum Bactericidal Concentration)", "LD50", "Therapeutic index"], a: 0, hint: "MIC = أقل تركيز مثبط." },
      { q: "Beta-lactamase (Penicillinase) production is a mechanism of:", type: "mcq", options: ["Antibiotic synergism", "Antibiotic antagonism", "Antibiotic resistance", "Selective toxicity"], a: 2, hint: "هذا الإنزيم 'يدمر' المضاد الحيوي (مثل البنسلين) قبل أن يعمل." },
      { q: "Which of the following is NOT a mechanism of antibiotic resistance?", type: "mcq", options: ["Enzymatic destruction (e.g., Beta-lactamase)", "Altered target site", "Decreased permeability/efflux pump", "Increased synthesis of the target"], a: 3, hint: "البكتيريا لا تقاوم عن طريق زيادة تصنيع الهدف، بل العكس هو الصحيح (تغيير الهدف)." },
      { q: "Combining Penicillin and Gentamicin is an example of:", type: "mcq", options: ["Synergism", "Antagonism", "Resistance", "Indifference"], a: 0, hint: "التآزر (Synergism) يعني أن 1+1 = 3 (التأثير المشترك أقوى من مجموعهما)." },
      { q: "Which antibiotic is known for causing 'Red Man Syndrome' if infused too quickly?", type: "mcq", options: ["Penicillin", "Vancomycin", "Tetracycline", "Ciprofloxacin"], a: 1, hint: "يحدث بسبب تحرر الهيستامين السريع." },
      { q: "Which antibiotic is associated with 'grey baby syndrome'?", type: "mcq", options: ["Chloramphenicol", "Streptomycin", "Penicillin", "Erythromycin"], a: 0, hint: "يحدث في الأطفال حديثي الولادة لعدم قدرتهم على معالجة الدواء." },
      { q: "Which drug is used to treat Tuberculosis (TB)?", type: "mcq", options: ["Isoniazid (INH)", "Rifampin", "Ethambutol", "All of the above"], a: 3, hint: "علاج السل يتطلب دائماً مزيجاً من عدة أدوية (RIPE)." },
      { q: "Isoniazid (INH) specifically inhibits the synthesis of:", type: "mcq", options: ["Peptidoglycan", "Mycolic acids", "Proteins", "Folic acid"], a: 1, hint: "هذه الأحماض هي المكون الشمعي المميز لجدار خلية بكتيريا السل (Mycobacteria)." },
      { q: "Polymyxins are antibiotics that:", type: "mcq", options: ["Inhibit cell wall", "Inhibit protein synthesis", "Disrupt the cell membrane", "Inhibit DNA synthesis"], a: 2, hint: "تعمل كـ 'منظفات' (detergents) تذيب الغشاء الخلوي، وهي سامة للكلى." },
      { q: "'Selective toxicity' means the drug is:", type: "mcq", options: ["Toxic to all cells", "More toxic to the pathogen than the host", "Only toxic to the host", "Not toxic at all"], a: 1, hint: "السمية 'الانتقائية' هي المبدأ الذهبي للعلاج الكيميائي: استهداف الميكروب دون الإضرار بالمضيف." }
    ]
  },
  general_tf: {
    title: "Basic Knowledge Test (True/False)",
    questions: [
      { q: "Gram-positive bacteria stain red after staining.", type: "tf", a: false, hint: "اللون الأحمر (السافرنين) هو الصبغة المضادة. موجبة الجرام تحتفظ باللون البنفسجي الأول." },
      { q: "Gram-negative bacteria contain a thin layer of peptidoglycan.", type: "tf", a: true, hint: "ولهذا السبب تفقد اللون البنفسجي بسهولة وتأخذ اللون الأحمر." },
      { q: "Mycoplasma is the only bacterium that does not have a cell wall.", type: "tf", a: true, hint: "لهذا السبب، المضادات الحيوية التي تستهدف جدار الخلية (مثل البنسلين) لا تؤثر عليها." },
      { q: "Spores are a method of bacterial reproduction.", type: "tf", a: false, hint: "هي وسيلة للبقاء (Survival) في الظروف القاسية، وليست للتكاث." },
      { q: "Mesophiles grow best at 37°C.", type: "tf", a: true, hint: "Meso تعني 'متوسط'، وهي درجة حرارة جسم الإنسان." },
      { q: "Obligate anaerobes die in the presence of oxygen.", type: "tf", a: true, hint: "الأكسجين سام بالنسبة لها لأنها تفتقر للإنزيمات (مثل الكاتالاز) لتحييده." },
      { q: "Sterilization is the elimination of all microbial life forms, including spores.", type: "tf", a: true, hint: "هذا هو الفرق الرئيسي بين التعقيم والتطهير." },
      { q: "Disinfection kills bacterial spores.", type: "tf", a: false, hint: "التطهير يقتل معظم الميكروبات، لكنه لا يقضي على الأبواغ المقاومة." },
      { q: "The Autoclave uses dry heat for sterilization.", type: "tf", a: false, hint: "الأوتوكلاف يستخدم بخار (حرارة رطبة) تحت ضغط. الفرن (Oven) هو الذي يستخدم حرارة جافة." },
      { q: "Penicillin works by inhibiting protein synthesis in bacteria.", type: "tf", a: false, hint: "البنسلين يهاجم جدار الخلية (Cell wall)." },
      { q: "Tetracycline works by inhibiting the 30S ribosomal subunit.", type: "tf", a: true, hint: "مضادات حيوية أخرى (مثل الماكروليدات) تستهدف وحدة 50S." },
      { q: "Plasmids are an essential part of the bacterial chromosome.", type: "tf", a: false, hint: "هي قطع DNA إضافية (Extrachromosomal) خارج الكروموسوم." },
      { q: "Pili are used for bacterial motility.", type: "tf", a: false, hint: "الأسواط (Flagella) هي التي تستخدم للحركة. الأهداب تستخدم للالتصاق." },
      { q: "The capsule helps bacteria resist phagocytosis.", type: "tf", a: true, hint: "تجعل البكتيريا 'زلقة' ويصعب على خلايا المناعة ابتلاعها." },
      { q: "The Log Phase is the fastest phase of bacterial growth.", type: "tf", a: true, hint: "تُعرف أيضاً بالمرحلة الأسية (Exponential) حيث تتضاعف البكتيريا بأقصى سرعة." },
      { q: "An antiseptic is used to disinfect inanimate surfaces and tools.", type: "tf", a: false, hint: "المطهر (Antiseptic) يستخدم على الأنسجة الحية (مثل الجلد). المعقم (Disinfectant) هو الذي يستخدم للأسطح." },
      { q: "Endotoxin is found only in Gram-positive bacteria.", type: "tf", a: false, hint: "يوجد في البكتيريا سالبة الجرام (Gram-negative) كجزء من غشائها الخارجي (LPS)." },
      { q: "Normal flora is naturally found in the blood.", type: "tf", a: false, hint: "الدم يجب أن يكون معقماً (Sterile). وجود بكتيريا في الدم يعني عدوى." }
    ]
  }
};
